### ISSUE TITLE
Fulton recovery pack bugs charachter sprites.

### ISSUE THREAD

**Issue by Snownbloodyflowers** [Citadel-Station-13/Citadel-Station-13-RP#1167]
#### Brief description of the issue
Using a fulton recovery pack in the underdark makes player naked and prevents items from dropping

#### What you expected to happen
Beacon should drop futon items and or people.

#### What actually happened
Items and person stuck until admin intervention, play sprite naked while ascending.

#### Steps to reproduce
- Place beacon in under-dark
-link beacon to fulton system
-active beacon to yourself or other player character
-ascend permanently.

#### Code Revision
-2019-04-03
9094314542b0dac909bb3d94124a8db45cf1822c 
 
#### Anything else you may wish to add:
- Underdark was also broken that round.

**Comment by realbuffalowing** [comment]
I have tested this and not seen this result. This must have just been a bugged round! I'm sorry this happened.
