### ISSUE TITLE
Mapping Error

### ISSUE THREAD

**Issue by MichaelMaCleod007** [Citadel-Station-13/Citadel-Station-13-RP#119]
#### Brief description of the issue
After firing up the Tesla I noticed Security on Asteroid 3 was not getting power, so I went to investigate and found that the power cable in Cargo Emergency Closet was not hooked up properly and had to re-wire it.

#### What you expected to happen
That the power cable would actually be hooked up.

#### What actually happened
Had to re-wire it.

#### Steps to reproduce
- Power Station
- Notice Security is not getting power
- Look in Cargo Emergency Closet

#### Code Revision
- Server revision:  - 2018-06-13
10322db71313c802fbbaca749d19228eab1ccd19 
 
#### Anything else you may wish to add:
- Cargo Emergency Closest on Asteroid Level 3
![ss13snafu](https://user-images.githubusercontent.com/33614698/41408145-b03b22e4-6f9f-11e8-90bb-87b88ca1d9df.JPG)

**Comment by realbuffalowing** [comment]
this was fixed at some point.
![fixed](https://user-images.githubusercontent.com/42501819/44381676-64c38e80-a4df-11e8-82cd-a90ecc53677a.png)
