### ISSUE TITLE
Wormhole futon recovery packs broken on certain objects

### ISSUE THREAD

**Issue by Snownbloodyflowers** [Citadel-Station-13/Citadel-Station-13-RP#1326]
#### Brief description of the issue
Wormhole futon recovery of certain objects fails silently.

#### What you expected to happen
Attaching an object makes it spawn around the area of the futon beacon

#### What actually happened
Mining drill clamps and heads will fail silently and not show up. Ore boxes will sometime show up.

#### Steps to reproduce
- Place a futon beacon corner on two sides by a wall.
- Leave and go to a non station Z-level
- Futon items to said beacon.

#### Code Revision
Server revision:  - 2019-04-22
cf08f34e39637878628823be173ec8a1b2499116 
 
#### Anything else you may wish to add:
- I think it might be a underdark issue.

**Comment by realbuffalowing** [comment]
im confused, can you provide more detail on the steps to reproduce this bug? thank u

**Comment by Snownbloodyflowers** [comment]
Literally place a beacon, use a futon pack on most items (large drill bits, locked crates). They will never appear.

**Comment by buffyuwu** [comment]
can u confirm if this is still an issue, i quietly made changes to the frs and didnt update this post since

**Comment by buffyuwu** [comment]
update: yeah it works now

**Comment by buffyuwu** [comment]
this is fixed as of either #1554 or #1304
