### ISSUE TITLE
Cannot finish air alarms

### ISSUE THREAD

**Issue by ghost** [Citadel-Station-13/Citadel-Station-13-RP#1403]
#### Brief description of the issue
It is impossible to finish air alarms after the stage of applying the frame to the wall

#### What you expected to happen
BE able to add wires/board to the air alarm

#### What actually happened
Nothing. Most likely a runtime.

#### Steps to reproduce
Use metal to create frame.
Grab frame, and make Air alarm on wall
Try to add the board/wires

#### Code Revision
- 2019-06-02-8c1f4fee60e97b406da26839d0326d5ef3930e1c
 
#### Anything else you may wish to add:
- May be the same for all other frames applied to the walls.

**Comment by ForFoxSake** [comment]
Your steps to reproduce don't include wrenching the frame down, which is a required step for air alarm construction.

**Comment by Snownbloodyflowers** [comment]
Wrenching the frame down? It is also possible to straight up apply it via clicking on the wall with it in hand.

**Comment by Tename** [comment]
Can someone close this?

**Comment by Tename** [comment]
@nik707 Just to make sure I am not stupid I tried to replicate this and couldn't, this is no longer a problem.

**Comment by buffyuwu** [comment]
@nik707
