### ISSUE TITLE
Constructed Airlocks don't have wires.

### ISSUE THREAD

**Issue by Ol-Vinny** [Citadel-Station-13/Citadel-Station-13-RP#1405]
#### Brief description of the issue
When you make an airlock (Only tried standard) and then tried to get to the wires, (screwdriver then multitool or wirecutters) the tab for wires just dosen't show up.

#### What you expected to happen
To be able to see the list of wires, and cut, pulse, or attatch signallers.

#### What actually happened
Nothing.

#### Steps to reproduce
- (Step 1) Create a standard airlock from scratch.
- (Step 2) Attempt to modify the wires.
- (Step 3) Cry

#### Code Revision
8c1f4fee60e97b406da26839d0326d5ef3930e1c 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Ol-Vinny** [comment]
After some more testing, I think this is caused by naming the airlock with a pen before finishing it. Still unsure, but I've had it work when I didn't try to name it and not work when I did. Small sample size though.

**Comment by Snownbloodyflowers** [comment]
I'll take a look. Do me a favor and see if partially deconstructing (but not turning the airlock frame back to metal and reconstructing the airlock) causes the issue.

**Comment by ForFoxSake** [comment]
I think I've run into this one before, but can never reliably reproduce it.
Sometimes door modifications appear to cause the door fail at some point, causing runtimes with certain interactions - I'm assuming.
If anyone sees this happening, please make a note of what specifically happened and if you can cause it to happen again.

It'll be much easier to fix if we can reproduce it reliably.

**Comment by Snownbloodyflowers** [comment]
The issue is with the strange hack that Polaris/Vore (I think Polaris?) handles access requirements. I don't fully understand the reason nor the method it works since changing access IDs gives me a large number of runtimes.

**Comment by nik707** [comment]
Couldn't reproduce. Reopen if reproduction becomes easier.
