### ISSUE TITLE
Entertainment Monitor Cameras

### ISSUE THREAD

**Issue by Eimras** [Citadel-Station-13/Citadel-Station-13-RP#1413]
#### Brief description of the issue
Entertainment Monitors list the NCS Northern Star News Feed as a potential choice.

#### What you expected to happen
Seeing as this is not the Northern Star, be a different name or removed.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
Server revision:  - 2019-06-05
0f50bab1a8e4efceb8f7385597264c145a6d9151 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/9496888/59191876-bc0a1c80-8b4e-11e9-9d0a-9a5e6ec1bc45.png)

**Comment by peeesh** [comment]
thats just the default press drone name. ill look into it
