### ISSUE TITLE
Research Director does not accumulate off-duty time as CO

### ISSUE THREAD

**Issue by chefferz** [Citadel-Station-13/Citadel-Station-13-RP#1414]
When playing the Research Director, you accumulate off-duty time for science, and not CO. 

Code Revision

    Server revision: - 2019-06-05
    0f50bab1a8e4efceb8f7385597264c145a6d9151

**Comment by peeesh** [comment]
yeah because its science. intentional

**Comment by chefferz** [comment]
It's not intentional. CO means Commanding Officer AKA A head department, It accumulated off-time at some point in the past, but for some reason it has stopped, hence the issue.

**Comment by nik707** [comment]
I'm actually gonna leave this as is.
