### ISSUE TITLE
Shuttle error

### ISSUE THREAD

**Issue by Airinnann** [Citadel-Station-13/Citadel-Station-13-RP#1437]
Reported error with the supply shuttle not actually arriving on station

Supply crew called supplies and the shuttle was registered as arrived

Shuttle never actually arrived on station with the supplies, instead claiming it had arrived and could be sent away.

Unknown if this is constant but it happens seemingly at random, simply reproduction involves just ordering the shuttle.

#### Code Revision
69b7a2e2217c4070403fc8990859654be37235a3 
 
#### Anything else you may wish to add:
As stated it appears to be happening randomly and multiple times

**Comment by nik707** [comment]
This is one of those things I've looked over and toiled on for hours and can never nail down a cause.

**Comment by buffyuwu** [comment]
It's going to happen until someone writes a better shuttle system unfortunately
