### ISSUE TITLE
Left arm from bioprinter has a blank icon

### ISSUE THREAD

**Issue by Beeskee** [Citadel-Station-13/Citadel-Station-13-RP#1439]
#### Brief description of the issue

The left arm, as printed from a bioprinter, has a blank icon. If you put it in your pack you can never take it out again.

#### What you expected to happen

It to have an icon

#### What actually happened

It didn't have an icon, was not interactable once stored in inventory

#### Steps to reproduce
- (Step 1) print a left arm at the bioprinter
- (Step 2) put it in your pack
- (and so on) regret

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
Server revision:  - 2019-07-02

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Friggs** [comment]
I've reproduced the issue on my end.

![image](https://user-images.githubusercontent.com/18521438/61394937-ddff6900-a889-11e9-94cc-cac7dc22e93a.png)

**Comment by chefferz** [comment]
Double check that the person you're attempting to print a limb from doesn't have a cybernetic limb on their character creation screen, because it will do the above blank icon if that is the case, or if they don't have one period.

**Comment by Friggs** [comment]
In the case of my screenshot, the blood was taken from the default human species.

**Comment by chefferz** [comment]
Yes, that's how it works, but if the person you took blood for has, on their character creation screen, that specific limb as missing or cybernetic, it won't print out in the limb printing machine period.

**Comment by Friggs** [comment]
This is test number 2, with a random unedited character.

![image](https://user-images.githubusercontent.com/18521438/61897144-0e738280-aedc-11e9-86d5-f5126c127320.png)

Set to human, limb set to normal:

![image](https://user-images.githubusercontent.com/18521438/61897223-3d89f400-aedc-11e9-8430-28cea36a0046.png)

After printed in backpack:

![image](https://user-images.githubusercontent.com/18521438/61897951-dcfbb680-aedd-11e9-8801-3d7d64a4725b.png)

**Comment by nik707** [comment]
Looked into it, and can find literally no reason for it occurring. Will be returning to this later with a fresh mind

**Comment by buffyuwu** [comment]
buffy will fix
