### ISSUE TITLE
Player-controlled corgis can't *bark

### ISSUE THREAD

**Issue by yorii** [Citadel-Station-13/Citadel-Station-13-RP#1471]
#### Steps to reproduce
- ahelp can I be a corgi plz
- *bark

#### Code Revision
Server revision:  - 2019-08-08
012c5ef6d17d6cb79b3daa735b670248cc8ff762

**Comment by nik707** [comment]
This is something that would have to be fixed through snowflake code or something stupid, and tbh it's not worth fixing as this is "working as intended"
If you wanna bark, just say literally anything and you'll bark  or yip.
