### ISSUE TITLE
[ENDEAVOR] Cargo stuff FUBAR

### ISSUE THREAD

**Issue by YuriDaruski** [Citadel-Station-13/Citadel-Station-13-RP#1490]
#### What actually happened: Crates were missing. 
In set of two separate orders, 4 supply crates were ordred, only two arrived. 
Second order was 2 collector crates, only one arrived. 

Test of four separate items, labled test 1 - 4 as the reasoning, 'test 1' failed to arrive, doors jammed. 

#### Steps to reproduce
- Order items
-Approve items
-Sent shuttle

#### Code Revision: 2019-08-28
afc8950b0a6602ae2b07464f760659947eb8f70f  - (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- third order caused doors to jam, cargo's doors opened, the shuttles did not, shuttle failed to undock with last order and was forced launched

**Comment by Andromeda-K22** [comment]
I literally have no idea why this is happening. I'm trying to fix it.
