### ISSUE TITLE
[Endeavor] General Feedback

### ISSUE THREAD

**Issue by HzDonut** [Citadel-Station-13/Citadel-Station-13-RP#1491]
#### Brief description of the issue
Fuck the rest of the formatting for this one. So two issues I noticed, not related to bugs, are the engineering layout and the bar. With engineering it just looks...really _bad_ with how it's smushed right up against the elevator the way it is, and the engine area looks rather cluttered for my tastes. Plus if that thing goes nuclear, the elevator is GONE with how close it is to the shaft. With the bar, it's not really my complaint so much as something everybody else wouldn't shut up about, but it's "too small" apparently. God forbid people find other places to AFK in besides the bar, right?

Oh, right. As for positive feedback: the layout of the whole map's piss easy to navigate (unlike the tether, which confused me for multiple shifts when i first saw it) and I'm enjoying a return to more...traditional layouts for departments. Traditional being "closer to the usual ss13 maps instead of tether snowflake nonsense". It feels familiar and cozy. Plus hey, 5 condensed z-levels vs. _fucking seven_ huge ones like the tether is great.

Found this ladder in Research maint. Looks kinda...janky. https://gyazo.com/cf473c684ac261983ae4eb9f40670bea

The VR area sends this message EVERY time you step onto the green tiles, gets a bit spammy. No idea if that's fixable. https://gyazo.com/d8a8c262c5227502b3998629ed1893bd

As a final note: some signs around to point people TO the stairs and/or elevator would greatly help navigation.

All in all, 7/10. Fix the listed stuff for it to go up to a 8/10 :)

**Comment by Andromeda-K22** [comment]
Elevator will be resolved.
