### ISSUE TITLE
[ENDEAVOR] VR Janibots break when you get on

### ISSUE THREAD

**Issue by YuriDaruski** [Citadel-Station-13/Citadel-Station-13-RP#1492]
#### Steps to reproduce
- Go into VR
- Load up the Yacht SIM 
- Go to the janitor closet
-Get on the janicart
-Watch as it poofs from under you

#### 2019-08-28
afc8950b0a6602ae2b07464f760659947eb8f70f 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Andromeda-K22** [comment]
Probably a code issue.
