### ISSUE TITLE
[ENDEAVOR] Outpost missing doors

### ISSUE THREAD

**Issue by YuriDaruski** [Citadel-Station-13/Citadel-Station-13-RP#1493]
#### Doors in some areas of the outpost found via the mining shuttle are missing, 
Dorms, Bathrooms for sure, haven't seen all rooms. 

Assumedly some appliances are missing as well. The diner there only have utensils but no appliances or food supplies. One would assume it would come with at the least a microwave but, I am not the map maker.

**Comment by Andromeda-K22** [comment]
Resolved.
