### ISSUE TITLE
[ENDEAVOR] Head Offices: Unnessicary Seperators, Security Issues

### ISSUE THREAD

**Issue by ForFoxSake** [Citadel-Station-13/Citadel-Station-13-RP#1494]
Skipping the template because this is map feedback, and things like "What I expect to happen" aren't relevant.

Four of the Six head offices have these unnecessary desk window separators in them. They serve no real purpose, as anyone allowed into one of these offices is usually trusted enough to not start fucking around with shit behind the desk. 
(It also distracts from the respect a head is supposed to command, if they first have to retreat behind a cage to speak to their employees.)

I'm omitting a screenshot of the CE office, since it appears vaguely sensible in split deign, with nothing particularly valuable on the "employees side" of the prison cell design.

CMO's Office:
![End_CMO](https://user-images.githubusercontent.com/16629824/63840222-997ee700-c978-11e9-8fd1-b6553962eb75.png)
The closet is on the wrong side of the separation, defeating the point of having the separation.

RD's Office:
![End_RD](https://user-images.githubusercontent.com/16629824/63840251-a7cd0300-c978-11e9-8e1c-3a7155dfd22c.png)
The table on the north side has an AI core chip and a Teleporter control chip on it. The photocopier and papershredder being on the other side of the glass mean you would have to cross the separator to perform paperwork duties.
So, absolutely no reason for this separator to be here either.
The RD also doesn't get a fax machine.

Now we come to the meat of this issue. The CD's office:
![End_CD](https://user-images.githubusercontent.com/16629824/63840274-b1ef0180-c978-11e9-8e0b-6aca4177715f.png)
At least everything valuable is on the correct side of the separator this time.
...Except for everything upstairs, that is. The real issue with that is that, being up the stairs means it's possible to barricade yourself in, or even attack from above.

So, in conclusion to the separators: They're not serving their purpose, they're just in the way.
They would also seem to suggest that they're supposed to be used in conjunction with office door controls, but no such office door control buttons exist in any of the offices.

Moving on to security issues with head/command/bridge area:
All offices are exposed either to maintenance or a public hallway, and in all cases have only one wall thickness and the CD's office even has a doorway facing a public hallway.
The poor HoP's office doesn't even get reinforced walls.

The deck 2 bridge entrance doesn't have an APC and starts depowered.
The bridge can be broken into from maint, requiring only that the front window be smashed.
There are two CMO stations on the bridge, both with identical computers.

PS: ~~The CD's office has two sets of stairs on one tile.~~
![End_Stairs](https://user-images.githubusercontent.com/16629824/63840299-bc110000-c978-11e9-8282-b44b5c45da7c.png)

Edit: Would have been sensible to spell check BEFORE posting.

**Comment by ForFoxSake** [comment]
Alright, struck out that last bit then, since that would make it a code issue not a mapping one.
How strange.

**Comment by Andromeda-K22** [comment]
CMO's office moved, windows removed. RD office windows removed, HoP office reinforced. RD has been given a fax machine. I don't see how public-facing Rwalls is really an issue, but the issues with the CD's office have been resolved.

It's likely most of the 'security' issues with the public facing rwalls will be resolved in an in upcoming command remap. Bridge entrance resolved.
