### ISSUE TITLE
[ENDEAVOR] Virology Machine Missing

### ISSUE THREAD

**Issue by ForFoxSake** [Citadel-Station-13/Citadel-Station-13-RP#1495]
Simple issue: Virology is missing the centrifuge/antibody machine, without it the lab is useless.

Screenshot:
![End_Viro](https://user-images.githubusercontent.com/16629824/63840919-bd8ef800-c979-11e9-8967-ecc16941b95b.png)
As screenshot shows: Virology only has an analyser, incubator and isolator, making it impossible to create virus dish samples, or antibody vials.
Also, for some reason there are two refrigerators?
(The one on the left appears to be the correct one for the department.)

**Comment by Andromeda-K22** [comment]
![image](https://user-images.githubusercontent.com/21302924/64069348-e7644b00-cc15-11e9-834f-abb759acd94b.png)
Resolved.
