### ISSUE TITLE
[ENDEAVOR] Atmospherics Issues

### ISSUE THREAD

**Issue by ForFoxSake** [Citadel-Station-13/Citadel-Station-13-RP#1496]
Found three issues immediately in atmospherics:
![Atmos_Cyan](https://user-images.githubusercontent.com/16629824/63842996-91757600-c97d-11e9-803e-f4a783101a01.png)
The cyan pipe here (the Air-to-Supply pipe) is unnecessarily long. It goes off screen, then hooks back around on itself to go back a quarter of the way.
This pipe is also going to be highly pressurized the whole shift, making it nothing but a nuisance to anyone trying to modify pipes in the area.
There's even a dead pipe leading nowhere in the bottom left of the room, that would serve the same purpose as this pipe, with only a fraction of the distance covered.

![Atmos_Portables](https://user-images.githubusercontent.com/16629824/63843209-e5805a80-c97d-11e9-974b-696241ef54e0.png)
These are in the way of the hallway. Considering the amount of empty tiles there are on this map, it shouldn't be too hard to cut these six into the wall so that they're not in the way of people trying to walk past each other in a central hallway.

![Atmos_Canisters](https://user-images.githubusercontent.com/16629824/63843334-237d7e80-c97e-11e9-8e86-4c95f5ce2515.png)
These canisters need to be contained, either in a separate room or glass windoors. As it stands, when these break (and they will break regularly) there's a good chance it could kill someone stood in the room.
(This same issue applies in Xenobotany. These are the two highest concentrations of canisters on the ship, and they all need isolating from the workspaces they're stored in.)

**Comment by Snownbloodyflowers** [comment]
The cyan loop also needs a shutoff valve incase anyone decides to mess with the loop. Same for the scrubbers (not that we've had 200+kpa on them)
