### ISSUE TITLE
[ENDEAVOR] Rant and critiques about the new map. 

### ISSUE THREAD

**Issue by Jakksergal** [Citadel-Station-13/Citadel-Station-13-RP#1497]
Alright, this is going to be a mixture of opinions and objective feedback on the new map being demo'd as I write this. I would consider myself an experience mapper, though I don't work particularly on this codebase. I'm responsible for Engineering and Security on the Tether for those that don't know my involvement.

#### Overview
- SS13 does not cater well to organic designs, i.e. curves, which the Endeavor seems to have a lot of. The general egg-shaped exterior makes it difficult if not impossible to efficiently utilize space effectively which leads to my next issue with the general flow of the map. You can achieve curvature on a larger scale with greebles. See the 3rd bullet point.
- The "Shape then fill" methodology this map took creates a lot of issues regarding the use or rather the misuse of space. I can tell the creator thought of a general shape, mapped that out, then filled the interior and did not compromise on the exterior in the slightest to make the departments function the best they can. There is a lot of wasted space across the staggering five Z levels. The Southern Cross used a shape and stuck with it but the mappers were willing to compromise the exterior shape to accommodate the department's needs and this would work to the advantage of the department. Medical now has windows to space in their patient rooms and engineering has direct exterior access. These are things that are much harder to accomplish when you don't compromise on the set shape.
- There is very little verticality incorporated into the map's design despite it being five Z levels. What I mean by this is that Z transitions in departments feel like afterthoughts to cram in that last bit of space required for a minimally functional department. 
- Diagonal R-walls are the same thing as double R-walls and this hurts me on a spiritual level.
![image](https://user-images.githubusercontent.com/5105765/63841536-d8407d00-c937-11e9-91df-1f15a489e1dc.png)
- While the vertical hallway design is functional from mindset of getting from A to B quickly it is very prone to causing station-wide blockages. There are few hard atmos blockages though being so far into a practically underground station makes this a very minor issue.
- The main hallways feel souless with no distinct characteristics between the Z levels. While visually unappealing it is also disorientating until you recognize "Oh, that door there means I'm on Z4, not Z5." Personally I separate parallel hallways between Z levels by 2 or 3 tiles and add turns to switch sides of the hallway below/above when needed. I feel this technique keeps the advantages of close-by hallways while also adding more options to make hallways unique. Alternatively you can add outcroppings full of seating, vendors, and other minor things to have things stand out just a touch more.
- The mix of quarter-tile floor markings and the modular type used in the Tether is not very visually appealing. It looks like you're walking between two. 
- Please use the proper directional sprites for corners of the modular floor tiles. This just looks bad:
![image](https://user-images.githubusercontent.com/5105765/63841485-be069f00-c937-11e9-843b-3e49efc8101e.png)
- This sort of ties in with the above bullet but there are not enough windows. 
- All airlocks are absolutely and unnecessarily massive. I suspect cycling is painfully slow because of this. A 3x2 airlock is usually all that's needed depending on its main function. A simple exterior access airlock or docking clamp only needs a 1x1 space and a vent inside because you're realistically only going to be briefly walking through it with no equipment in tow.
- The elevator is larger than a dorm room or a head of staff's office. This doesn't need to be the case and isn't so much of an issue as it is a pet-peeve.
- Adding breaks in long windows such as the bridge or security briefing is a very easy way to add visual appeal. Walking by the pillars between the window will give the player a bit more visual stimulation. You might not think it's much but it goes a long way.
- Inline stairwells with such a small gap between them is bound to cause issues. Some clients (Probably all but I haven't confirmed) have a frame or two that's skipped when transitioning via stairs. Them being so close means it's pretty easy to accidently walk up 2 or 3 more Z levels than you wanted.

Now onto departments.
#### Engineering.
- Double blast doors are unnecessary. It would be easier to just increase the rad resistance of blast doors than to explain with engineering has this weird trapezoidal shutter system.
- While I have not tested this recently, a SMES being ejected can only be thrown over so many tiles before it stops dead. I believe it was five tiles before it stops being thrown and I doubt anyone's messed with the code to make it go farther. The reinforced floors outside the chamber probably need to go. Please test this in your next revision if you intend on keeping this map.
- Atmos is a warehouse as it should be but it's incredibly barebones. Pipes are not colored correctly and there are a few cardinal sins for user-friendly atmos design aside from the coloring. Pipes shouldn't go under machinery and R-walls unless absolutely necessary not only because it's a pain in the ass to replace those pipes (for R-walls anyway) but it obstructs the player's vision when they're reading the layout. 
- Atmos' canisters have no doors or windoors protecting the rest of atmos from them if they pop. I think you took inspiration from the Tether's toxins lab with the conveyors below them but this really isn't necessary and is a bit annoying.
- CE's office and EVA should be swapped in position. This would allow the CE's office to have lobby access and have EVA hook up directly to Atmos and the workshop. Unify the two EVA storages as well, there's no point in keeping the suits separated.
- The scrubber and pump filling stations are out in the hallway but could be recessed into it and given windows to atmos to break up the monotony  When you move them, be sure to think ahead on how an engineer might expand them since this is a very common practice on servers that actually have engineering issues.

#### Security
- It is laughably easy to escape the brig. At any moment you are either one door away from a yakety-sax until the lobby doors open if they're not already (They will be as officers rush in to try to taze the perp's ass) or a public-facing R-wall. Although to the map's credit those walls are right next to the elevator and cargo foyer so it's at least in the public's vision most of the time.
- There is no visitation. While without mechanical function it serves as a way to easily transport items between outsiders and inmates and allows for RP.
- Solitary has no sleepers in it, nor does the brig itself. Sec's going to have a pileup of SSD on a bad day.
- 3x hallways in departments are plain-and-simple not necessary. You could gain a lot of useful space by shaving off one tile from every hallway.
- You could shave off some of security's lankiness by condensing the briefing room to be more reasonable. I adore the little office rooms, though, and I'm going to steal that in a heartbeat.
- The open space above the brig beside the head of security's offices aren't significant enough to serve any purpose and just makes it easier for people with wings to escape. 
- The forensics lab hallway and surrounding maintenance just don't need to be there. I don't believe it adds anything and takes up a lot of space you could be using more effectively.
- It's a walk to get anywhere in sec, especially from the forensics lab to evidence storage.

#### Medical
- I'd tell you what I think about medical but I don't know where to find it. Medical is so far away from everything in terms of walking distance. For a 5Z station it should be as central as possible. 
- The distance from surgery to the AMS (Advanced Medical Scanner) is huge. 
- Likewise the distance between resleeving and the morgue is a lot. You'll end up dragging dead/SSD bodies in sight of the public lobby which is a bit of a pain for the doctors just trying to do their job.
-The virology shuttle is cute but personally I think it should use one of the [material]_hull style walls to differentiate it from the station and prevent sprite merging. By no means is this necessary.
- Psych is the perfect size for an Oxycontin party but a little large for an RP room. It's also lacking grilles in the windows.
- The break room is pretty sad. Usually the medical break room is pretty posh comparatively. 
- Medical's missing the aux storage room that normally houses medical hardware like extra IVs, wheelchairs, and a syringe gun.
- The CMO's office looks like a parole officer's office with those reinforced windows. Just a gripe.
- The Rescue Suit is just.. sitting out in the open on a table right next to the lobby. There's already an existing EMT bay for it.
- The EMT bay really doesn't need R-walls. 

#### Research
- Again, 3x hallways are not necessary inside departments. It's wasted space.
- Xenobotany's really lacking in trays. You could expand it out to the edge of space by having that maint tunnel dip down a Z level and then go back up later on in maint. This would also fix the dead end that maint tunnel has.
- Putting mining right next to research was honestly a great idea. You could add a simple conveyor or disposal pipe to put those diamonds straight into the hands of the scientists, though. Could free up a touch of space for mining to use.

#### Cargo
- My only complaint with cargo itself is that it's a big bland and large. 
- Mining not being next to cargo is usually a bad movie but since mining's right next to research I guess it's not so much of a big deal. 

#### Civilian
- The chapel's mosaic floor decals are meant to be used on tiled floors, speaking of, the dark floor tiles in the chapel is a classic look. 
- Additionally the more I look at the misaligned door the more I can feel my blood vessels expanding.
- The kitchen, bar, and botany are very nicely designed. If you have nothing else to look at for inspiration, this is what you should try to emulate for the other departments. There does need to be a meat hook to properly cut up some creatures, though.
- The library's.. somehow feeling very crampt and oversized at the same time. There is a massive hallway beside it but there are only four shelves in the library main room.
- The """"study"""" rooms having a lock is pointless if any yahoo can peak in on your yahoo from maint. Either move the study rooms to the edge of space or give them tint control. Or both.
- The Maltese Falcon shouldn't be mapped in fully functional. There don't need to be 3 bars on an oversized station. I like the vibe it gives as a sort of brothel but organizing something like that should be on the players. This space is now always a bar and never going to be what an engineer or maint diver wants it to be.
- I love the exercise and relaxation center sort of vibe you're giving with the pool area but I do have a gripe as an engineer main that the sauna room exists. Things that the engineers are able to build and have people actually participate in is already in short supply. This is a personal gripe, however. I'm not sure if other engineers feel the same way.

$$$$ Command.
- The bridge has a really stellar design but does need a bit of refinement. It's massive in that central area. 
- The bridge meeting room/overlook should just go straight to space. The windows aren't electrocuted either.
- The captain's quarter's are lavish but feel extremely hostile to the person entering. On top of that it's one door or one R-wall from being breached.
- The NT breacher suit in EVA should be in a more secure location. It has considerable armor values.
- The AI's core is only one R-wall away from the vagrants that inhabit the station. I couldn't imagine living in these sort of conditions. 
- This is just overkill.. 
![image](https://user-images.githubusercontent.com/5105765/63843427-3a4eb180-c93b-11e9-8144-ab8d595d1af8.png)
- Tcoms being the size of Atmos is a trend that should have died the moment it was nessisary to put with the station and not on its own Z level. Tcoms being huge on the Tether is a result of it being copied and pasted from The Northern Star's map which was copied and pasted from Baystation 2014's Box station which was only massive because it had room to spare. 
- There is no way in hell Command needs their own VIP lounge. It's just begging to form elitist cliques which needless to say is something no one wants. 

#### Exploration
- That shuttle is dummy thicc, the clap of its propulsion is going to alert all the simple mobs in the Z level. Seriously though it needs to be slimmed down.
- May god have mercy on your soul. At least engineers don't ever have to deal with double shuttle walls.
![image](https://user-images.githubusercontent.com/5105765/63844181-99f98c80-c93c-11e9-94bd-5cae37a5b02c.png)

Edit: Reorganized a bit of text to make some bullet points flow better in case someone comes back to this for design advice or something.
Edit 2, this time it's personal: Removed some lines per Killian's comment.

**Comment by ForFoxSake** [comment]
I feel I need to say, I don't see a single point on this list that seem like things that could be put off or put aside. But I personally didn't include them in my issues for two reasons: 1. I felt like if I were the only person to bring up the wasted space issues, then I'd seem like I was needlessly poking at the map's creative design. And 2. Jakksergal's done a far better job wording this than I ever could have.

From what I've seen of the Endeavor so far, if everything listed here could be fixed, then we would have a map to rival the Tether... But a lot of these issues aren't simple fixes, and there's several issues that require some departments to be fairly completely overhauled.
Above all else though, really, it needs to feel more like a space ship, and less like a prison.

**Comment by KillianKirilenko** [comment]
> I'm not much of an exploration player but I think they're under equiped

Yeah, no. This map actually has better equipment for Exploration than Tether (all the Explorers get their own binocs, for starters, and there's an extra exploration voidsuit) and the EXTRA THICC shuttle has a bodyscanner in addition to the sleeper (whereas Tether shuttle has just a sleeper). Anything more than starting gear is overprep a lot of the time unless your team is really big, which is rare.

_That said_, the shuttle is an oversized abomination and needs to go on a diet. The crew/passenger seats should be visible from the cockpit, so that the pilot can see buckling and non-radio responses to buckle-checks/etc. - and they should just be closer together in general so folks can chat and interact during the flight without it seeming like they're shouting across a fucking room!

I recommend switching it to a design closer to the current/Tether shuttle but somewhat more streamlined. I have a couple of alt. designs that might work (https://i.imgur.com/8xZDHQs.png), but they only have one real way in/out which makes for much slower deployment. If I could do this myself I would, but last time I tried fiddling with the airlock setups/configuration it didn't work out great and I didn't have the patience to debug it.
