### ISSUE TITLE
[Endeavour] Engineering Department and general map issues

### ISSUE THREAD

**Issue by Snownbloodyflowers** [Citadel-Station-13/Citadel-Station-13-RP#1499]
#### Brief description of the issue
List of running mapping issues in engineering.
#### List of issues
-Engineering ladders around the SMES have the "deck X" signs on top of the ladder.
-Engine room lacks an eject button
-CE office lacks an eject button
-CE office lacks a Ce hardsuit (maybe it was lag?) and a set of superior goggles
-AI upload, AI core, PDA log servers have no/inactive turrets and is missing controls
-Telecoms lacks turrets/turret controls
-the ship exterior is only one r-wall wide.
-Chapel has a strange bug I can't find yet regarding it spawning with <80kpa.
-Drone fabricator does not sync even when detected.
-VIP lounge has hidden wall that leads to the bridge.
-Bridge lacks announcement devices, and Keycard devices.
-Secure areas lack electrified grilles.
-Research security outpost has wrong access permissions.
-Telecoms can be broken into by cutting down a single regular wall and breaking glass
-Atmospherics SMES is not in it's own room with APC
-Telecoms, security, cargo, command, medical, engineering lack their own SMES with APCs.
-Atmospherics lacks toxin (empty) canisters. Same for engine storage.
-Engineering SMES doors will runtime.

#### Anything else you may wish to add:
-I sleep. Ask questions and I explain later.

**Comment by Andromeda-K22** [comment]
-Resolved
-Resolved
-Resolved
-Check your locker/Resolved
-Resolved
-Resolved
-Not An Issue
-Can't Reproduce
-??? Code issue probably. 
-Resolved
-Vague.
-Resolved
-Resolved
-Atmospherics does not need it's own substation area.
- Not An Issue (Deck-Level subgrid schema).
-Why is this an issue?
-Can't Reproduce.

**Comment by Snownbloodyflowers** [comment]
-Toxins needed for removing containment in engine loop.
-The doors were caused by some VERY strange behavior regarding it. Might be from the area overload event?

**Comment by Andromeda-K22** [comment]
Engine filtering already vents to space.
