### ISSUE TITLE
Continually Flashing Grub Hiding Spots

### ISSUE THREAD

**Issue by Nethaufer** [Citadel-Station-13/Citadel-Station-13-RP#1512]
Whenever a grub is disturbed from its hiding spot the machine continues to flash. Only way I've seen it stop happening is after killing a fully grown grub and its machine stops flashing.

**Comment by buffyuwu** [comment]
> Tried to fix, but im a retard. so ill come back to this

come back to it

**Comment by RobotAlice** [comment]
This can be closed now. #1687
