### ISSUE TITLE
Science southern airlock to planet lets anyone inside

### ISSUE THREAD

**Issue by Kersakof** [Citadel-Station-13/Citadel-Station-13-RP#1522]
#### Brief description of the issue
As a miner, I was able to get into the first floor of science without any issues.

#### What you expected to happen
I expected to get into the station.

#### What actually happened
I got into science instead.

#### Steps to reproduce
- (Step 1) Be a miner
- (Step 2) User the airlock on planet from outside science to get inside.
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
Server revision:  - 2019-09-10
24c260566301df685d776ea07724406ef2682595 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by nik707** [comment]
See above
