### ISSUE TITLE
Veggie Momo invisible

### ISSUE THREAD

**Issue by Lupinius** [Citadel-Station-13/Citadel-Station-13-RP#1556]
Upon preparing the meal Veggie Momo, the finished product is invisible

Correct or ad icon/sprite
- (Step 1) Add ingredients to microwave
- (Step 2) cook
- finished product invisible

#### Code Revision
Server revision:  - 2019-10-08
8e814f9eff08255cafb656f7f39193e03b7805f0

**Comment by nik707** [comment]
fixed by #1582
