### ISSUE TITLE
v2 aerostat has doubled airlocks

### ISSUE THREAD

**Issue by Hatterhat** [Citadel-Station-13/Citadel-Station-13-RP#1566]
#### Brief description of the issue
Airlocks are doubled up on the aerostat. Guessing it might be related to #1519, much like how runtime maploading tends to get goofy.
#### What you expected to happen
Single airlocks on V2's aerostat. As it has been. Historically.
#### What actually happened
Double-spawned airlocks. Very weird.
#### Steps to reproduce
- literally just go to v2 bruh
#### Code Revision
Server revision:  - 2019-10-21
0bc43babc7f1991b6059e26bcc6f3925c6034738 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/31829017/67247473-1aada400-f427-11e9-84be-429d9771c2a4.png)

**Comment by nik707** [comment]
i quite literally cannot even get the map to open so ill get back to this

**Comment by Mewchild** [comment]
Is this issue still happening? Looking at it in the map file revealed nothing

**Comment by Mewchild** [comment]
Just checked on the live server. This issue can be closed @nik707 
![image](https://user-images.githubusercontent.com/13400422/72734939-755ab700-3b60-11ea-9f37-80d825b0fa8b.png)
