### ISSUE TITLE
Communicator news app does not work

### ISSUE THREAD

**Issue by Tename** [Citadel-Station-13/Citadel-Station-13-RP#1576]
#### Brief description of the issue
I opened the borg internal Communicator to check the station announcement history and non of the news channels displayed anything.

#### What you expected to happen
News

#### What actually happened
No news just eternal greyness

#### Steps to reproduce
- Open Communicator
- Click News
- Click a channel

#### Code Revision
- Server revision:  - 2019-10-24
f5c1ac0be846874a04d7f22c7b0521ef0e1d9e96

**Comment by nik707** [comment]
Unable to replicate
