### ISSUE TITLE
Can't put taser cooling upgrades in K9 Units

### ISSUE THREAD

**Issue by Tename** [Citadel-Station-13/Citadel-Station-13-RP#1578]
#### Brief description of the issue
If you try to put the Taser cooling upgrade into the dogborg security unit it says, "Upgrade mounting error! No suitable hardpoint detected!"

#### What you expected to happen
Pew... pew... pew ----> Pew pew pew

#### What actually happened
Upgrade mounting error! No suitable hardpoint detected!
Upgrade mounting error! No suitable hardpoint detected!
Upgrade mounting error! No suitable hardpoint detected!
Roboticist: It doesn't fit

#### Steps to reproduce
- Get dogborg
- Get taser upgrade
- Open dogborg
- Try to put in
- It doesn't work
- Cry

#### Code Revision
- Unable to provide the server restarted and updated, this occurred in the round on 10/27 10:00 PM
- But I have also seen it in Server revision: - 2019-10-24
f5c1ac0be846874a04d7f22c7b0521ef0e1d9e96

**Comment by nik707** [comment]
Fixed by #1581
