### ISSUE TITLE
[Biggy] Medical huds are broken

### ISSUE THREAD

**Issue by Tename** [Citadel-Station-13/Citadel-Station-13-RP#1579]
#### Brief description of the issue
When taking damage the hud will go down properly, but after healing it won't return. This results in people being indicated in critical condition from earlier that are now healed walking around.

The temp in game fix for this is to remove your ID and putting it back on, that seems to force an update.

#### What you expected to happen
Health to go down and up on the hud.

#### What actually happened
Health went down but not up.

#### Steps to reproduce
- Get a hud and put it on
- Stab yourself 72 times with an Iridium fork you just used to eat half a taco you found in maints
- Heal yourself
- You are still being shown as hurt on hud

#### Code Revision
- Server revision:   - 2019-10-28
b29e9680aae939f4178c07641991c2f38ea6faff 

#### Anything else you may wish to add:
- https://media.discordapp.net/attachments/323935657821077524/638243094462201867/Nice_HP_nerd.png

**Comment by buffyuwu** [comment]
i can't replicate this. can you confirm this is still an issue?

**Comment by Tename** [comment]
I haven't seen it as often recent I think I saw it once with a robot who just got brain transplanted but this might have been fixed by something... Ill pay more attention for a bit and close this if I see nothing @buffyuwu

**Comment by Tename** [comment]
Think this may be fixed, closing
