### ISSUE TITLE
Service borg and Service dog issues

### ISSUE THREAD

**Issue by Tename** [Citadel-Station-13/Citadel-Station-13-RP#1587]
#### Brief description of the issue
Service hounds and the gripper itself need upgrade, this is a bit list of problems that need fixing.
- The gripper can not pick up oven trays
- The gripper can not pick up fryer trays
-  Plant bag should be replaced with a food bag (It can pickup food and most plant stuff).
- The cyborg drink synthesizer is missing Sugar, Space spices, milk, and Honey
- The service gripper can not grip prest-spray
- Service hound tongue starts dry.
- The gripper can not pick up sticks/straws

#### Code Revision
- Server revision:  - 2019-10-29
821b82a95f82ba0e95ce013197637d421b48cb6b

**Comment by Tename** [comment]
Also, the service hound has a pointless multitool but maybe there is a reason?

**Comment by Tename** [comment]
Not a bug, but the Rapid Service fab could be expanded to produce more things, as of right now its only useful purpose is Pint glasses, perhaps simple snacks, more glass types, and I don't know plushies?

**Comment by VailTheWolf** [comment]
Multi tool is used in botany to modify the planters last I checked. Never botany'd before so don't quote me.

**Comment by Tename** [comment]
Ah, makes sense
