### ISSUE TITLE
Dog borg tongues clean sinks while trying to drink from them.

### ISSUE THREAD

**Issue by Tename** [Citadel-Station-13/Citadel-Station-13-RP#1588]
#### Brief description of the issue
Try to refill your tongue via sink and you end up refilling and drinking from it, wasting water while you gain water.

#### What you expected to happen
To only lap up water

#### What actually happened
To lap up water and clean the sink

#### Steps to reproduce
- Lick sink
- Clean sink
- And get water

#### Code Revision
-  Server revision:  - 2019-10-29
821b82a95f82ba0e95ce013197637d421b48cb6b

**Comment by VailTheWolf** [comment]
Everything cleans the sink while you draw water.
