### ISSUE TITLE
Freshly Constructed Airlocks Cannot be Hacked and Lack Title

### ISSUE THREAD

**Issue by Knouli** [Citadel-Station-13/Citadel-Station-13-RP#1594]
#### Brief description of the issue
Airlocks that are freshly built from a 'new' circuit board, or those rebuilt from previously existing airlocks cannot be interfaced with through a multitool. You are able to screwdriver open their panel but none of the traditional means of accessing and adjusting their wires work (multitool, bare hand clicking, wirecutters) as the menu simply will not open.

Additionally, any custom name given to the airlock will not be preserved and will revert to it's default for the class of airlock constructed.

#### What you expected to happen
Standard airlock behavior. Screwdrivering open the panel to expose the wires that could then be interfaced with by a multitool of similar implement.

#### What actually happened
I was unable to open the menu required to hack the airlock. Nor did it preserve the name given to it through the construction process.

#### Steps to reproduce
-Build from scratch an airlock, or rebuild an old one after removing the electronics, using a pen on the unfinished airlock to give it a custom name
-Finish the airlock and observe it does not have the custom name given to it
-Screwdriver open panel
-Attempt to use a multitool to open the hacking menu, fail to open the wire menu

#### Code Revision
2019-10-30   cf946717b19b9f650f4922f5ff1a5255da38e54d 
 
#### Anything else you may wish to add:
Here is a fresh built airlock lacking its custom name, and unable to be hacked with its panel open and a multiool in hand.
![image](https://user-images.githubusercontent.com/25857923/67998295-5ec25500-fc2e-11e9-8690-86c1231fca5f.png)

Here is an airlock that was persistent since the start of the shift, displaying standard behavior.
![image](https://user-images.githubusercontent.com/25857923/67998307-6bdf4400-fc2e-11e9-9bf4-5d0121db4909.png)

**Comment by Knouli** [comment]
I depends on the type of airlock constructed, it would seem. Here's what I've been able to test thus far.

standard airlock assembly - broken
command airlock assembly - works
security airlock assembly - works
eng atmos airlock assembly - works
engineering airlock assembly - works
mining airlock assembly - works
atmospherics airlock assembly - works
research airlock assembly - broken
DEFAULT (Nothing added) Multi-tile airlock assembly - broken

![image](https://user-images.githubusercontent.com/25857923/67998853-4eab7500-fc30-11e9-9af0-752ef61282e0.png)

There might be some other factor in play here that I don't see? But, I can't be certain, and I've had standard airlocks I've built in the past crap out on me. Seems an effective workaround for now is to build an airlock assembly from the list that -does- work.

**Comment by Knouli** [comment]
Finally, for sanity's sake, you ARE able to hack airlocks that are inclusive within that list that are effected- SO LONG AS they are part of the initially generated world map. Such as this two tile airlock, which is part of the list that cannot be accessed if freshly built - yet this example of the stairwell two tile airlock that was there since the beginning of the round may have its wire menu accessed.

![image](https://user-images.githubusercontent.com/25857923/67999034-0a6ca480-fc31-11e9-9f04-9de56faa4e37.png)

**Comment by Snownbloodyflowers** [comment]
Runtime found. 
proc name: attack hand (/obj/machinery/door/airlock/attack_hand)
usr: Snow n chrysanthemums/(Mevludin Queiroz)
usr.loc: (Main Station Atrium (53, 68, 5))
src: the Airlock (/obj/machinery/door/airlock)
src.loc: the floor (53,67,5) (/turf/simulated/floor/tiled)
call stack:
the Airlock (/obj/machinery/door/airlock): attack hand(Mevludin Queiroz (/mob/living/carbon/human))
the Airlock (/obj/machinery/door/airlock): attackby(the wirecutters (/obj/item/weapon/tool/wirecutters), Mevludin Queiroz (/mob/living/carbon/human), 1)
the wirecutters (/obj/item/weapon/tool/wirecutters): resolve attackby(the Airlock (/obj/machinery/door/airlock), Mevludin Queiroz (/mob/living/carbon/human), 1)
Mevludin Queiroz (/mob/living/carbon/human): ClickOn(the Airlock (/obj/machinery/door/airlock), "icon-x=18;icon-y=13;left=1;scr...")
the Airlock (/obj/machinery/door/airlock): Click(the floor (53,67,5) (/turf/simulated/floor/tiled), "mapwindow.map", "icon-x=18;icon-y=13;left=1;scr...")

**Comment by buffyuwu** [comment]
PR #1630 will allow you to rename airlocks via multitool and also describe them. it also fixes the wires = null issue. <3
