### ISSUE TITLE
Putting flour in a meat pocket makes meatballs

### ISSUE THREAD

**Issue by Tename** [Citadel-Station-13/Citadel-Station-13-RP#1595]
#### Brief description of the issue
lol wtf

#### What you expected to happen
not to make meatballs

#### What actually happened
made meatballs

#### Steps to reproduce
- flour
- meatpocket
- meatballs

#### Code Revision
- Server revision:  - 2019-10-30
cf946717b19b9f650f4922f5ff1a5255da38e54d 
 
#### Anything else you may wish to add:
- thanks aloysius very cool

**Comment by buffyuwu** [comment]
Hey! What did you expect to happen? As in, if I were to fix this really quick what should I make it create.

**Comment by Tename** [comment]
> Hey! What did you expect to happen? As in, if I were to fix this really quick what should I make it create.

Nothing it can be used to create unlimited meatballs

**Comment by buffyuwu** [comment]
replacing the quantity of protein the uhhh meat pocket has from 3 to 2 should fix this though makes it less filling i think
