### ISSUE TITLE
Minor Chapel Wiring Issue + Orphaned Disposal Pipe

### ISSUE THREAD

**Issue by Nethaufer** [Citadel-Station-13/Citadel-Station-13-RP#1648]
After the change in wiring done to the Chapel, the APCs are now not charging. I attempted to find the issue via VV but I couldn't find it so I went with the brute force method of replacing the wires manually with a different color. I replaced the pink wires on Station 1, the Z-level crossing pink wire, as well as all the wires up to the chapel office, and once I swapped those wires out they started charging again, including the areas connected to wires I didn't replace. Swapped them back to pink ones and it still works. I have a feeling one of the wires before the cabling splits to the Chapel APC has an issue. Note, swapping out just the wires before it passes into the chapel, before the maint door, didn't work. It's only when I replaced the wires under the door and into the chapel that it worked properly. The wiring under the door or the curve wire just before it may be set up incorrectly.

![dreamseeker_2020-01-10_09-48-58](https://user-images.githubusercontent.com/7095406/72166578-1c846500-338f-11ea-841b-07b4d15068c9.png)

In my attempts to fix, I also found an orphaned length of disposal pipe just beneath the chapel office door. It's not connected to either the disposal pipe just to the south and there aren't any pipes to the north. The disposal chute is properly connected, however, so I figure this is just a leftover from when the chapel might have been renovated.

![2020-01-10_09-50-26](https://user-images.githubusercontent.com/7095406/72166815-8f8ddb80-338f-11ea-8597-590e2b9bc5c1.png)

**Comment by Mewchild** [comment]
This was closed via #1644
