### ISSUE TITLE
Medbay lobby windoor can be broken infinitely

### ISSUE THREAD

**Issue by cherostavik** [Citadel-Station-13/Citadel-Station-13-RP#1667]
#### Brief description of the issue
The windoor in medbay lobby on the left, next to the implanters, can be broken without actually being removed, making it infinitely breakable

#### What you expected to happen
The door to be removed

#### What actually happened
Once it is broken, it can be broken over and over, dumping more and more parts on the floor

#### Steps to reproduce
- (Step 1) Hit the windoor until it breaks
- (Step 2) Keep hitting it

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision:  - 2020-01-18
44ea44481e80b67b7d013da113a78ef40f441a7d 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

Medbay lobby, left side, windoor

**Comment by RobotAlice** [comment]
This can be closed now. #1687
