### ISSUE TITLE
Loadout options allow for nested storage

### ISSUE THREAD

**Issue by Mewchild** [Citadel-Station-13/Citadel-Station-13-RP#1693]
#### Brief description of the issue
Certain loadout options can allow you to nest storage: A dufflebag inside a dufflebag inside a backpack, for example. All these containers can be used by click-dragging, meaning you can have roundstart Bluespacebag+ levels of item storage

#### What you expected to happen
There to be a check in place, and not spawn items inside containers too small to hold them

#### What actually happened
Selecting two dufflebags and a purse will equip one duffle, spawn the purse and the other duffle inside the equipped one.

#### Steps to reproduce
- In loadout, navigate to the utility tab
- Select the options to spawn with a Black Dufflebag, a Purse, A regular Dufflebag. As many options as your job will allow you to take.
- Join the round, and open the duffle you have equipped.

#### Code Revision
- https://github.com/Citadel-Station-13/Citadel-Station-13-RP/commit/cbe98f449f37eed104ac921204095c00f9a54da8
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/13400422/75311320-ff5f0500-581b-11ea-8f0e-4d6db6175990.png)

**Comment by RobotAlice** [comment]
On it.
