### ISSUE TITLE
Loadout Options sometimes reset

### ISSUE THREAD

**Issue by Mewchild** [Citadel-Station-13/Citadel-Station-13-RP#1742]
#### Brief description of the issue
On occasion, the loadout options you have saved will nuke themselves

#### What you expected to happen
Loadouts to be saved properly

#### What actually happened
All selections on a single loadout tab are reset, save for the accessory tab

#### Steps to reproduce
Unknown. Issue is a sporadic bug.

#### Code Revision
Master commit: 18b7036366f34a8074d0ff73713ab3e345bef7ae

**Comment by buffyuwu** [comment]
I've never experienced this, and never seen this occur. Can you reproduce this on a local server somehow? If so, what are the steps you would take?
