### ISSUE TITLE
Broken/Missing Chameleon Clothing Sprites

### ISSUE THREAD

**Issue by drofoljaelisglis** [Citadel-Station-13/Citadel-Station-13-RP#1745]
#### Brief description of the issue

Certain options on the chameleon clothing selection, I believe in **every** category, have missing sprites and will either show up as invisible, or will show a generic broken sprite image rather than be fitted with the corresponding sprite.

#### What you expected to happen

To be wearing an outfit that matches what I selected in the chameleon clothing selection menu.

#### What actually happened

I was dressed with some red error text, and on my body was an orange shirt that had multiple question marks and the word "HONK" on it. Occasionally, I wouldn't even get **that**, but rather I would be completely lacking a sprite in the broken outfit's slot as if I weren't wearing anything to begin with.

#### Steps to reproduce

1. Acquire Chameleon Kit
2. Select a clothing option in (I believe) any of the categories. 
2a. Two guaranteed examples to let you see what I mean: With a pair of chameleon shoes, select the "imperial leg guards" option, and with a chameleon jumpsuit, select the "pink latex jumpsuit" option.
3. Look in horror as you realize you're either naked, or now clothed only with some red error text.

#### Code Revision
 BYOND Version: 512.1488
Server revision compiled on: 
Master commit: 18b7036366f34a8074d0ff73713ab3e345bef7ae 
The following pull requests are currently test merged:
#1710: 'Revert "stack crossover automerge and alt click splitting because clicking on 50 sheets of metal is not something that is okay  "' by Nethaufer at commit 25e52dc150 

Local commit: 85affd142f8697d4707679c95572b8a12dc7470c
Server tools version: /tg/station 13 Server v3.2.5.1

#### Anything else you may wish to add:

![chameleon jumpsuit broken](https://user-images.githubusercontent.com/61575370/77723028-82ef4b80-6fac-11ea-91be-6bbbd5c06f22.PNG)
![honk shirt](https://user-images.githubusercontent.com/61575370/77723054-939fc180-6fac-11ea-8a74-fc630031fd76.PNG)

**Comment by buffyuwu** [comment]
So, the clothing in the chameleon kits use var/global/list/clothing_choices, meaning _every clothing item in that global list could be tried by the player._ Unfortunately, not every clothing option fits every race/species/type. I don't see this as an issue, and have no plans to redesign the global/list/clothing_choices to be race/species/type specific lol
