### ISSUE TITLE
Stacks don't split when clicked on with an empty hand

### ISSUE THREAD

**Issue by Beeskee** [Citadel-Station-13/Citadel-Station-13-RP#1746]
#### Brief description of the issue
Stacks don't split when clicked on with an empty hand
It pops up a dialogue but then nothing happens.

#### What you expected to happen
The stack to split

#### What actually happened
Nothing

#### Steps to reproduce
Get the stacked Phoron in medical
Switch to an empty hand
Click the stack of phoron in your off hand
enter the number to split
watch as nothing happens

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Master commit: 7c9b97c8096f7752f18616cba251b450de811689 
Local commit: 28caa0ee66a1f32d8b9727b82f022e67eb3f16b2
Server tools version: /tg/station 13 Server v3.2.5.1

#### Anything else you may wish to add:
You can use the phoron in Medical

Headsets in lockers seem to be permanently stacked/stuck together due to this.

**Comment by Captain277** [comment]
Alt-Click the stack, instead of clicking with an empty hand.
