### ISSUE TITLE
Missing Food/Drink Sprites

### ISSUE THREAD

**Issue by drofoljaelisglis** [Citadel-Station-13/Citadel-Station-13-RP#1763]
#### Brief description of the issue
Certain food and drink items have no sprite attached to them.

#### What you expected to happen
To get beautiful aesthetic cool drink/food sprite.

#### What actually happened
I got a lousy glass of water (in the case of drinks) in place of my awesome nice sprite, and sometimes got nothing at all/invisible sprite (in the case of food).

#### Steps to reproduce
-Create Food/Drink Item with Missing Sprite
-Get Nothing(aka invisible), or a generic sprite in it's place

#### Code Revision
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: c66b7d0b7607fbe9583b918c070504f1419624d8 
The following pull requests are currently test merged:
#1757: 'Revert "stack crossover automerge and alt click splitting because clicking on 50 sheets of metal is not something that is okay  "' by Nethaufer at commit e67c3d8981 

Local commit: 55ac191e2629758e4fcf8c3d5f2025bf6c75f3cd
Server tools version: /tg/station 13 Server v3.2.5.1

 
#### List of confirmed missing/broken sprites:
-Poached Egg

**Comment by BlackMajor** [comment]
Think kevinz gave what you're referring to its sprites by now.
