### ISSUE TITLE
Atmospherics is One Large Area

### ISSUE THREAD

**Issue by Nethaufer** [Citadel-Station-13/Citadel-Station-13-RP#1772]
#### Brief description of the issue
Atmospherics seems to be one giant area, when it comes to things like air alarms. A tank bursts in atmos storage and the entire area gets locked down. This also becomes an issue if someone tries to clear the leak by panic siphoning (while not advisable it still some people do it) the ENTIRE atmospherics area starts to panic siphon. Have a feeling that each room isn't divided into separate atmos areas.

#### What you expected to happen
A single room being made unsafe and only that room being locked down.

#### What actually happened
A single room being made unsafe and the entire atmos department locking down.

#### Steps to reproduce
- Render a room unsafe atmospherically
- Watch as all the shutters in atmospherics go down
- Wonder who did this and why

**Comment by RobotAlice** [comment]
This is on tether, right? Worth clarifying for posterity.

**Comment by KasparoVy** [comment]
Didn't even know we ran the Tether map after seeing us on the dope ship past couple weeks.
