### ISSUE TITLE
Service borg booze synthesizer

### ISSUE THREAD

**Issue by EvilEnchantress** [Citadel-Station-13/Citadel-Station-13-RP#2073]
#### Brief description of the bug
My booze synthesizer will not allow me to swap what I'm synthesizing and will not refill

#### What you expected to happen
I expected to be able to pick and choose what I dispensed and to be able to replenish my booze

#### What actually happened
Not that

#### Steps to reproduce
- (Step 1) Select service dogborg (I am specifically using pink)
- (Step 2) select your booze synthesizer and activate by clicking on it or hitting hot key use equipment, z by base I believe, on other servers this brings up a thing in chat that I would be able to click on to choose what I synthesize.
- (Step 3) Us up all your ale and it won't replenish, I've been out of ale for 30 ish minutes.

final notes, my apologies if I sent this to the wrong place, it is an issue on the rp server so I just hope I'm not doing something incorrectly.

**Comment by Crystal9156** [comment]
Can confirm, I just attempted this today, 10/4/20 and had the same issue, the synthesizer seems to be broken.
