### ISSUE TITLE
Moving Diagonally While Ventcrawling Ejects You

### ISSUE THREAD

**Issue by TalkingCactus** [Citadel-Station-13/Citadel-Station-13-RP#2112]
#### Brief description of the bug
While ventcrawling, you can leave the vent at any time by moving diagonally.

#### What you expected to happen
To not be able to move diagonally while in vents.

#### What actually happened
I was able to move diagonally while in a vent, which ejected me.

#### Steps to reproduce
- Climb in a vent.
- Move diagonally.

#### Code Revision
- 39b8835cd3f493547afe4262c061e85e72c83ef6
 
#### Anything else you may wish to add:
- 🍝

**Comment by TheLordME** [comment]
Can reproduce, I am now looking into the issue, will comment again, if I have found an fix.
