### ISSUE TITLE
Dough Cannot Be Tile-Grabbed By Food Bags UNLESS It Has Other Ingredients With It

### ISSUE THREAD

**Issue by drofoljaelisglis** [Citadel-Station-13/Citadel-Station-13-RP#2277]
#### Brief description of the bug

You cannot tile-gather dough with foodbags, UNLESS other ingredients like spaghetti is also on the same tile. Flat Dough and Dough Slices are, however, unaffected. Just the "dough" item is affected.

#### What you expected to happen

To be able to actually gather my dough as a Chef with my foodbag to make mass cooking less CBT.

#### What actually happened

I had to suffer by individually storing every ball of dough in my foodbag one by one, hand by hand, or alternatively drop something and then pick up that item, thereby circumventing the issue.

#### Steps to reproduce
-Acquire Dough (3u egg yolk / 1 egg 1 beaker + 10u Flour)
-Acquire Foodbag
-Attempt to pick up Dough with Foodbag
-Cry when it doesn't work
-Learn you can do it, for some fucking reason, when there's another ingredient on the same tile
-Cry again

#### Code Revision
BYOND Version: 513.1527
Server revision compiled on: 
Master commit: f6aba5984f647276909563a07445f91588f53c4e 
The following pull requests are currently test merged:
#2251: '[testmerge only] reverts async turbolift pr' by silicons at commit 228c4489cc 
#2276: 'Rat Race: Escalation' by Captain277 at commit 3f1326daa8 

Local commit: 13289f9d5c91c4c68c7824b81c89f681d1149439
Server tools version: 4.4.5
 
#### Anything else you may wish to add:
WHYYYYYYYY IS IT SO JAAAAAAAAAAAAAAAANK

**Comment by buffyuwu** [comment]
Just put an ingredient on the tile 4head /s

I looked into this and didn't find much success in resolving it, but it'll remain on my to-do's.

**Comment by RobotAlice** [comment]
Investigating.
