### ISSUE TITLE
CE window panes are uninteractible.

### ISSUE THREAD

**Issue by SweetBlueSylveon** [Citadel-Station-13/Citadel-Station-13-RP#2306]
#### Brief description of the bug
The windows infront of the CE's office work fine, but the window panels in front of them are completely uninteractible.  

#### What you expected to happen
You should be able to unscrew, pop the pane out, and unscrew it from the socket to move it out of the way. Every other window pane does this, except for the three lining the outside of the CE's windows.

#### What actually happened
You can't interact with these three window panes at all.

#### Steps to reproduce
- Go to the engineering lobby.
- Try to use screwdriver-crowbar-screwdriver on the three panes lining the outside of the reinforced windows.
- Try to do the same thing on the panels lining any other windows. (To show you how it should work.)
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/55075747/92425740-fb059400-f13c-11ea-9e37-94ef462182ff.png)

**Comment by TheLordME** [comment]
They are Interactable, like every other full window/border window combination.
You need to first disassemble the Fullwindow before you can access the border window.
