### ISSUE TITLE
Switchtool produces fake "switchtool tool"

### ISSUE THREAD

**Issue by SweetBlueSylveon** [Citadel-Station-13/Citadel-Station-13-RP#2308]
#### Brief description of the bug
You can use the switchtool to separate the tool options into individual items.

#### What you expected to happen
When you put the switchtool into your bag, either nothing happens, or the tool retracts.

#### What actually happened
When you select your tool. and put it in your bag, it'll add the "switchtool ____" as well, but taking up the same slot. It also doesn't take up any extra space unless you take it out and put it back in. These switchtool tools will also disappear if you reselect them on the on the switchtool.

#### Steps to reproduce
- Get a switchtool.
- Select any tool on it.
- Put it in your bag.
- It adds whatever tool you picked alongside your switchtool. And you can take them out and throw them around.

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/55075747/92429233-28a30b00-f146-11ea-8031-46803634d3dd.png)
![image](https://user-images.githubusercontent.com/55075747/92429247-33f63680-f146-11ea-8379-59c82d2047cb.png)
![image](https://user-images.githubusercontent.com/55075747/92429264-3d7f9e80-f146-11ea-95db-3b1f519e4832.png)

**Comment by SweetBlueSylveon** [comment]
![image](https://user-images.githubusercontent.com/55075747/92429295-525c3200-f146-11ea-9e7f-292b7be8d349.png)

**Comment by SweetBlueSylveon** [comment]
Update, these "Switchtool tools" can be used for constructing things. Such as the stunprod.

**Comment by buffyuwu** [comment]
@silicons this was fixed in #2346 iirc

**Comment by buffyuwu** [comment]
@Captain277
