### ISSUE TITLE
Borgs are able to interact with things on camera

### ISSUE THREAD

**Issue by upsetorandajin** [Citadel-Station-13/Citadel-Station-13-RP#2309]
#### Brief description of the bug
As the title states, borgs are able to interact with things on camera, not sure if they should in certain cases.

#### What you expected to happen
Take a light switch for example, if you click it through a camera as a Borg, nothing happens.

#### What actually happened
When exiting the camera mode, it is actually possible to interact with the light switch.

#### Steps to reproduce
Go into camera mode
Find a light switch
Click it
Notice nothing happens
Proceed to exit camera mode and while doing that rapidly click the light switch
Light switch will allow interaction

#### Code Revision
Master commit 01ffcdfd104474ef7fddb95dc6c2e98a95b7d973 
b5c69fdec000cda68d5045ee59486454e6e21e99
 
#### Anything else you may wish to add:
Might be possible to interact with a whole lot of devices this way. Will investigate myself as I play Borg a lot.

**Comment by RobotAlice** [comment]
I don't think this is a bug so much as just how synthetics interact with machines. AIs can interact with light switches through cameras also, for instance.

**Comment by upsetorandajin** [comment]
> 
> 
> I don't think this is a bug so much as just how synthetics interact with machines. AIs can interact with light switches through cameras also, for instance.

If so, then they're bugged by the fact that they can't always interact with certain things on camera unless they are in the process of closing the camera view.

**Comment by buffyuwu** [comment]
I believe the originally written intent for cyborgs was not to perform the functions of an AI.

**Comment by TheLordME** [comment]
Can not reproduce on live. @Captain277 or @silicons this is no longer an issue
