### ISSUE TITLE
I Can See Forever! - An Overmap Bug Involving Sensors Consoles

### ISSUE THREAD

**Issue by drofoljaelisglis** [Citadel-Station-13/Citadel-Station-13-RP#2319]
#### Brief description of the bug

Under certain conditions, you can get an advanced view than you normally would have. It involves the console to view the overmap map.

#### What you expected to happen

To not be able to see forever.

#### What actually happened

I was able to see forever.

Note: This bug does not go away if you leave the console, nor close your PDA window. It was tested and seems that someone else disengaging the sector map view does not boot you from your advanced view.

#### Steps to reproduce

[Tested at: Civilian Transport Sensors Console]
1. Open up Sensors Console
2. Engage Sector Map View
3. Grab PDA.
4. Open PDA.
5. Watch as your third eye is expanded and you can now see a much greater distance than you normally could.

#### Code Revision

BYOND Version: 513.1527
Server revision compiled on: 
Master commit: 6c56466a85edf41a69ea135ea27c8c5ce3e62cf5 
The following pull requests are currently test merged:
#2251: '[testmerge only] reverts async turbolift pr' by silicons at commit 228c4489cc 
#2304: 'Dark Corners of the Galaxy: The Awakening' by Captain277 at commit 8d0170b923 
#2311: 'Updates to the ship and overmap generation fixed. Prep for new Shuttle' by Enzo-Leon at commit 45eb02124a 
#2310: 'Xenolove: Zaddat RIGs, Phoronoid RIGs soon to come' by JennaSilverShark at commit 1a22eaab6e 

Local commit: 942337227d101d59fc5284b134d55caf23946354
Server tools version: 4.5.2

#### Anything else you may wish to add:

![bug baybeee](https://user-images.githubusercontent.com/61575370/93030954-e3fef000-f5db-11ea-8d51-037876c876b7.PNG)
![b r o k e n](https://user-images.githubusercontent.com/61575370/93030955-ea8d6780-f5db-11ea-8281-93730d50f969.png)
![sexy widescreen support](https://user-images.githubusercontent.com/61575370/93030964-f547fc80-f5db-11ea-85e4-9ebc67cf7751.PNG)

**Comment by TheLordME** [comment]
Unable to reproduce on 
Server revision compiled on: 2020-12-11
Master commit: c00f733d62bff050a3ef74391172e1e3f224f8ba 

Link of the attempt:
https://cdn.discordapp.com/attachments/296237931587305472/786859577315950592/Citadel_Station_13_-_HRP_2020-12-11_08-37-14.mp4
