### ISSUE TITLE
AI becomes unable to use cameras after witnessing a shuttle come back.

### ISSUE THREAD

**Issue by upsetorandajin** [Citadel-Station-13/Citadel-Station-13-RP#2360]
#### Brief description of the bug
As the title states, something went terribly wrong when I was watching the excursion shuttle come back through the cameras as an AI.

#### What you expected to happen
For the camera to continue working and seeing the shuttle returned.

#### What actually happened
As the shuttle returned, the screen turned black and I became unable to get camera view to work again, just stayed black. Upon relogging I was back at my AI core but unable to access any other camera even after using the Change Network command a couple of times and attempting to follow members of the crew.

#### Steps to reproduce
Become an AI
Have the excursion shuttle leave
In camera mode, go to where the excursion shuttle was
Have the excursion shuttle come back
As it comes back the bug should occur

#### Code Revision
BYOND Version: 513.1527
Server revision compiled on: 
Master commit: e5dc30745b858948b914a655a3fbc19060f9843a 
Local commit: e6d07594543721225fb191ff6c7c00d89546bff7
Server tools version: 4.5.2

**Comment by UrsaMajora** [comment]
I just experienced this bug with the departure shuttle. In specific I believe it's the AI Eye mob being gibbed because it was under where a shuttle would arrive.
