### ISSUE TITLE
Bl3pgun missing sprite

### ISSUE THREAD

**Issue by Scottbert85** [Citadel-Station-13/Citadel-Station-13-RP#2380]
#### Brief description of the bug
When I make a healgun at the exosuit fabricator, it has no sprite. I can only see it by alt+click examining the tile, which allows me to interact with it from the list and once picked up I can put it on an exosuit as normal.

#### What you expected to happen
The bl3pgun should have a sprite like every other item.

#### What actually happened
The bl3pgun has no sprite.

#### Steps to reproduce
Go to the exosuit fabricator and (once the technology has been researched and synced), print a BL-3 "Phoenix" healgun.

#### Code Revision
Unsure, last checked early morning 2020 Sep 26.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ThatOneTeshari** [comment]
Gonna look into it for you, been digging at the sprites for a bit now and yeah, the Medigun sprite is in, so it's just a code error to the sprite.

Should have fix out shortly.

**Comment by ThatOneTeshari** [comment]
Good news, after about two hours of trying to figure it out, the PR for the fix has been made.

**Comment by Mewchild** [comment]
@ThatOneTeshari In that PR, make sure you put in the first post that it closes this issue
