### ISSUE TITLE
Library's private study room light issue

### ISSUE THREAD

**Issue by harry3124** [Citadel-Station-13/Citadel-Station-13-RP#2397]
#### Brief description of the bug
The private Study Room and Library itself has the same light circuit, instead of being separated, causing either side's light switch to flick both side's light fixture.

#### What you expected to happen
When both rooms are turned off, when you turn on the light switch in the private study room, then only the private study room shall be turned on, instead of the rest of the library. Vise versa.

#### What actually happened
Both lights are turned on from interacting with any side of the light switch.

#### Steps to reproduce
- Interact with the light switch in the library.
- Interact with the light switch in the private study room.

#### Code Revision
- 3016d6a35ded1725410e0ce4a617db6bfed9d3dd

**Comment by Mewchild** [comment]
Easy fix, the study rooms need to be put into their own area. Only issue with that is a minor one, they'd need their own APCs. I can fix this in a day or two.
