### ISSUE TITLE
All hyperlinks that open into a web browser are no longer working as intended

### ISSUE THREAD

**Issue by izzyinbox** [Citadel-Station-13/Citadel-Station-13-RP#2442]
#### Brief description of the bug
Opening up hyperlinks from the game client mangles the URL once in the browser.
This happens for all links in chat, as well as buttons at the top of the right panel.
Likely one too many levels of, or misplaced text sanitization. 

#### What you expected to happen
One example, clicking the github button at the top and expecting to be brought to
`https://github.com/Citadel-Station-13/Citadel-Station-13-RP`
#### What actually happened
The link is transformed into
`%22https//github.com/Citadel-Station-13/Citadel-Station-13-RP"`
before being sent to the browser.
Note the leading `%22`, lack of `:` in `https//`, and `"` at the end.

#### Steps to reproduce
- Click on any link in game chat, be it OOC chat or character OOC notes as frequent examples.
or
- Click on any of the link buttons at the top (Wiki, Forum, Rules, GitHub).

#### Code Revision
BYOND Version: 513.1527
Server revision compiled on: 
Master commit: c52ce895aa2f97b16ef79aa60e18d6569418edbd 
The following pull requests are currently test merged:
#2371: '[WIP] Adds new explosions and ship creaking sound effects' by Enzo-Leon at commit 05342ae9ad 
#2427: 'Hard Boiled: A Citadel Story (Gives the Detective their .45 instead of a taser.)' by Captain277 at commit 53453da2ae 
#2424: 'PMD - Exotic Weaponry Update' by Captain277 at commit c58edbe80d 

Local commit: 69061a0b4965d203a79f791e6a3638a9f824f9fc
Server tools version: 4.5.4

**Comment by Zandario** [comment]
This was a internal issue outside our control.
Story is that Microsoft changed something without warning/announcement which fucked up something in byondwin.dll called the CLink class which basically opened links in the system's default browser via commandline

**Comment by LetterN** [comment]
byond issue, go update your byond to latest beta.
 close this @Zandario @silicons
