### ISSUE TITLE
AI can see ghost fingers.

### ISSUE THREAD

**Issue by UrsaMajora** [Citadel-Station-13/Citadel-Station-13-RP#2509]
Brief description of the bug
As an AI, you are able to see when ghosts around your eye are pointing to something.

What you expected to happen
You PROBABLY aren't supposed to see ghosts pointing at things in general. But yet, here we are.

What actually happened
I actually saw what the ghosts were pointing at. Not much to explain.

Steps to reproduce
-Step one: Be AI
-Step two: Have a ghost near your eye
-Step three: Have the ghost point at something
-Step four: Witness what the ghost points at as the AI

Code Revision
Master commit: 74a4b678206131cebc1573ba59728c28073f7fcf 
Local commit: affc7949be69dc36d738931d59e08d3774e191a0

Screenshot attached.
![dreamseeker_2020-11-21_21-36-42](https://user-images.githubusercontent.com/74837673/99893131-ef0c7700-2c41-11eb-80d1-808a0268465b.png)

**Comment by buffyuwu** [comment]
does this,.., really affect gameplay tho,.,., in any capacity,.,.,,

**Comment by buffyuwu** [comment]
^ above fix isnt a fix, disregard
