### ISSUE TITLE
Runaway Hologram

### ISSUE THREAD

**Issue by UrsaMajora** [Citadel-Station-13/Citadel-Station-13-RP#2510]
Brief description of the bug
The AI hologram can run away in the proper circumstances

What you expected to happen
The Hologram is supposed to stay in place when you select toggle hologram movement.

What actually happened
If there's no gravity, this is not the case. It just keeps going, long past the limits of the holopad. Watched it go from the bar to the end of the hall, far out of the confines of the holopad.

Steps to reproduce
- Be AI
- Have no gravity
- Activate a holopad
- Move one tile away any direction
- Toggle hologram movement and watch it run away

Code Revision
- Master Commit: 74a4b678206131cebc1573ba59728c28073f7fcf 
- Local Commit: affc7949be69dc36d738931d59e08d3774e191a0 

Anything else you may wish to add:
This is hilarious and I love it even if it's a bug.

**Comment by TheLordME** [comment]
Additional issue with AI holograms:
ghosting as AI(wipe/erase core) doesnt delete the hologram if the AI is currently using a pad.
