### ISSUE TITLE
Infrared Sensors are whack.

### ISSUE THREAD

**Issue by UrsaMajora** [Citadel-Station-13/Citadel-Station-13-RP#2591]
#### Brief description of the bug
The Infrared Sensors don't update their lasers.

#### What you expected to happen
The Infrared Sensors, when on an assembly, should update their laser once every couple seconds.

#### What actually happened
It triggers, and doesn't extend again for a couple minutes.

#### Steps to reproduce
- Print out from an Autolathe a Signaler and Infrared Sensor.
- Screwdriver both and make them into an assembly, screwdriver to secure.
- Set the Infrared Sensor's beam to visible (applies on invisible but easier to see this way) and on, drop it and move away.
- You will see the laser now (though it also doesn't work right when going sideways, different bug.)
- Walk into the middle of the laser to trip it. Walk out again and see that it doesn't reset.

#### Code Revision
Master commit: df28a83694efef8989bceff7d85db4f43b2b806b 
Local commit: 2f0da07950a2ac8b932dd55d425e9dd5bf85da01
 
#### Anything else you may wish to add:
It may be something small all things considered, since so many don't even know the infrared exists. But it is a useful little device assembly for a multitude of things.

**Comment by TheLordME** [comment]
Additional things that definitly dont work as intended with the infrared sensors:
Ghosts can trigger them,
Long range beams arent correctly generated
