### ISSUE TITLE
Energy Blade Coloring

### ISSUE THREAD

**Issue by Captain277** [Citadel-Station-13/Citadel-Station-13-RP#2597]
This isn't a bug, so much as an issue I can't figure out on my own.

_Expectation:_
Energy blades are sprited to accept a color overlay. The vars are there as well, at a cursory glance.

_Reality:_
Energy blade held icon starts as blue. Mob sprites are white with no color overlay generated. Changing the color turns the icon sprite white.

_To Reproduce:_
1. Turn it on.

If someone can look it over and figure out why the mob and icon sprites aren't accepting color overlays like they're meant to, I'd appreciate it.

**Comment by TheLordME** [comment]
I seem to have found the issue, as without cut_overlays() the sprite has the initial color and even changes it, until the overlays all add up to white, leaving cut_overlays commented out also means the turned off state still looks active.
tried to replace the cut_overlays() with a simple our_overlays.cut() didnt work and some other stupid Ideas my tired mind could come up with. going to look mor into it in 8-10 hours, after I slept.
