### ISSUE TITLE
Research toxins shouldnt vent

### ISSUE THREAD

**Issue by TheLordME** [Citadel-Station-13/Citadel-Station-13-RP#2624]
#### Brief description of the bug
The Toxins burn chamber and more specificly the "vent" are enclosed by the ship meaning the vent would actually just enlarge the burn chamber.

#### What you expected to happen
That a vent to space actually leads to space and is not enclosed by ship hull.

#### What actually happened
The vent for the burn chamber is enclosed by all sides with walls or maintenance tunnels.

#### Steps to reproduce
- Observe
- got to the Toxins lab
- check above and below decks for space
- fail to find actuall space.

#### Code Revision
-BYOND Version: 513.1536
Server revision compiled on: 
Master commit: 5e7fd4e0a6d485eb3f0a50e05c061cab0a3ef323 
The following pull requests are currently test merged:
2513: 'bandaid fix - cult/rat signals no longer do anything if it's not the main ship triggering because exploration shuttles causing a cult invasion on the actual station due to bad piloting on THEIR shuttle is STUPID' by silicons at commit 36ab5ea20e 
2596: 'Restores Dual E-Swords' by Captain277 at commit 1f1021fffb 
2594: 'Gives the Chaplain a Holster for the Null Rod' by Captain277 at commit dfa824080e 
2617: 'Grand Reopening: Nebula Gas Food Mart!' by Captain277 at commit c4b33fdad7 
2620: 'Medical Gear Unhugbox - Infections' by Enzo-Leon at commit 66997bd79f 
2618: 'Operation Cap icons renamed to work.[DNM]' by TheLordME at commit b63f9c1f84 
2622: 'Fixes / Adds Teshari Quartermaster Cloak Loadout' by nevimer at commit 22bf6ea0cc 
2623: 'Fixed a very small thing with the ERT suit' by SpessInquisitor at commit 82ecdee684 

Local commit: 8bc1a1ba3f5459f9b9065db6aab6d6f955c99688
Server tools version: 4.7.3
 
#### Anything else you may wish to add:
![grafik](https://user-images.githubusercontent.com/58342752/104698186-46463980-5711-11eb-9ae1-3f690e461d15.png)

**Comment by buffyuwu** [comment]
it looks like it does lead to several space tiles. are you saying there should be more space tiles?

**Comment by TheLordME** [comment]
no, the space tiles shouldnt be space tiles, above and below there are plating and maintenance tunnels.
Right now it works because the z-levels arent actually connected.
Just something for someone to consider when reworking the science department.
Venting and all works fine, but isnt logical from a 3D perspective

**Comment by ktoma36** [comment]
Has been fixed, moved toxins to where the firing range and circuitry lab was. The space tiles also caused issues with making phantom ship shields above and below it plus you could actually climb into space from the maint below

**Comment by TheLordME** [comment]
Cool cool
