### ISSUE TITLE
Trash pit constantly overpressurizes

### ISSUE THREAD

**Issue by Mewchild** [Citadel-Station-13/Citadel-Station-13-RP#2666]
#### Brief description of the bug
Due to the way disposals function, the trash pit overpressures every time a trash chute is used
To resolve this, a scrubber and vent need to be mapped into the Trash Pit

#### Code Revision
BYOND Version: 513.1533
Server revision compiled on: 
Master commit: ed1531bf2706a88dcff90616617bd0e5100cf690 
The following pull requests are currently test merged:
#2658: 'Vox Captain Damage Buff and Vox Ion Mob Addition' by Captain277 at commit bbe3a912b2 
#2656: 'Livin' In a Box/Adds Large Cardboard Box.' by Jaybirdnerd at commit b39e9d0793 
#2655: 'Nerfs Baymiss and Buffs Intrinsic Accuracy Across the Board' by Captain277 at commit ec6642c636 
#2650: 'Adds an Age gate' by buffyuwu at commit 0f8534365a 
Local commit: 4283ed2f9f93683af85261ab890af4db1812e9a7
Server tools version: 4.8.0

**Comment by Captain277** [comment]
The Trash Pit appears to have its atmospherics machinery updated. Please confirm the issue no longer exists and I will close this.

**Comment by rpilcrow** [comment]
It's still overpressurising.
Current best in-round fix is to keep its remote control set to 'on' so you can remotely panic siphon it down to 100kpa every now and then. 
Not sure if there's any mapping fix since air alarms don't really have any behaviour to automatically deal with overpressure.

**Comment by buffyuwu** [comment]
a tiny fan on the exit pipe tile might fix this lol

**Comment by silicons** [comment]
unfixable
disposals system intrinsically does this
there's no real way to fix this that doesn't involve an atmos refactor

feel free to prove me wrong gamers

**Comment by ktoma36** [comment]
This was for triumph right? If so this is most likely closable, we arent going back to triumph (hopefully)
