### ISSUE TITLE
Prosthetic Organs Cannot Be Attached - This Kills the Crew

### ISSUE THREAD

**Issue by Captain277** [Citadel-Station-13/Citadel-Station-13-RP#2679]
When first installed, or if in the mob on spawn, synthetic/prosthetic organs work fine.
If the organ is removed for any reason, and then placed back into the body, you cannot reattach it via the surgical steps. Most players will not notice this, and will complete the surgery without replacing the organ. This is often fatal.
Synthetic organs appear to attach automatically without player input the **first** time they are installed, and then **never** again.
To replace a synth organ, a brand new organ must be printed and applied.
There is no clear cause for this, and it was reported to be fixed last year. However, it is definitely still broken.

**Comment by buffyuwu** [comment]
can you find the fix for that? it might have been wiped when the upstream merge knocked a bunch of PRs out
