### ISSUE TITLE
In-shipping cargo shuttle belt 'teleports'

### ISSUE THREAD

**Issue by TheKnightofAura** [Citadel-Station-13/Citadel-Station-13-RP#2684]
#### Brief description of the bug
The top (problem child) belt on the cargo shuttle, to load crates onto the Triumph, sends things to the end of the line instantly

#### What you expected to happen
to behave like the bottom belt, moving things one tile at a time

#### What actually happened
get zipped from wherever you where on the belt, to the end of the belt

#### Steps to reproduce
- (Step 1) turn on upper cargo belt
- (Step 2) step on it
- (and so on) be yeeted

**Comment by buffyuwu** [comment]
conveyor code is messed up unfortunately, ill give it another look but it requires a whole rewrite when we can just.... not map them to move in that direction as a simple fix

**Comment by TheKnightofAura** [comment]
Rather have it like this then not mapped in this direction, honestly, at least for this instance. There was large fuss with both belts leading into the shuttle

**Comment by TheKnightofAura** [comment]
Closing this, as it's gone back and forth and is basically resolved at this point
