### ISSUE TITLE
Splitting your maps folder breaks the webmap

### ISSUE THREAD

**Issue by AffectedArc07** [Citadel-Station-13/Citadel-Station-13-RP#2707]
![image](https://user-images.githubusercontent.com/25063394/107887192-3716ff00-6efc-11eb-8389-5857813ae3f3.png)
Pick one and standardise on it, until then your webmaps wont update

EDIT: Southerncross is also borked
```
maps/southern_cross/southern_cross-1.dmm
Failed to load maps/southern_cross/southern_cross-1.dmm:
2090:48:bad digit 35 in map coordinate
```

**Comment by AffectedArc07** [comment]
Feel free to close this issue once it has been dealt with

**Comment by Zandario** [comment]
Will be dealt with, also surprised southern_cross is still there, that's like from two codebases up...
