### ISSUE TITLE
Glasses add chems to ChemMaster as they're being put in

### ISSUE THREAD

**Issue by rpilcrow** [Citadel-Station-13/Citadel-Station-13-RP#2738]
#### Brief description of the bug
Due to the OPENCONTAINER flag on ChemMasters, putting a glass into the Chem/Condimaster will add part of its chems to the reagent buffer as a standard reagent transfer. This means that you have to re-transfer the missing chemicals in the interface.

Beakers don't do this, as they have a list of machines that they do not add reagents to (which is a list present on every beaker rather than a global list, interestingly)

This obviously doesn't happen if the OPENCONTAINER flag is removed from the ChemMaster.

#### What you expected to happen
No transfers to happen unless there's already a container in there.

#### Steps to reproduce
- Fill glass with reagents.
- Add to the condi/chemmaster.

#### Code Revision
BYOND Version: 513.1533
Server revision compiled on: 
Master commit: 3e4de9670442e288ee3cf068894add8ce4381fe4
The following pull requests are currently test merged:
#2697: '[Testmerge only][Touches Deck 3] Adds new exiting medicine for patches and replaces/reworks the old ones' by TheLordME at commit 6d3e076022
#2729: 'what the fuck is atomization - fixes the last few tgui bugs' by lolman360 at commit 80bcac405b
#2732: 'Lavaland Should Spawn Rare Ore Now and Active Edge Fix?' by Captain277 at commit 7ac2d2a92a
#2731: 'Shuttle Thruster Band-Aid' by Captain277 at commit bf90287ecf
#2730: 'Map Updates - Deck 2 and 4. Now With 100% Less Pool-Shields ' by Enzo-Leon at commit 55f0ccbc0e
#2733: 'minor autocorrect fix' by buffyuwu at commit 1e7a4b3895
#2735: 'fixes tgui spamming the everloving fuck out of href logs ' by silicons at commit 5e239ffad9
#2734: 'kpa changes' by lolman360 at commit 64a44a54bb
#2736: 'replaces vorestation vore-vent preferences with a bitflagged event prefs with descriptions' by silicons at commit 34509d1eca

Local commit: 113a2d7756c2bae7787005aba14f279e7c9f2ddc
Server tools version: 4.8.0

**Comment by TheLordME** [comment]
I think its a remnant skill check, or an inproper removed one, that behaviour is similar to how BaySkill chemmasters acted when you lacked skills

**Comment by rpilcrow** [comment]
having taken a look at it, it's because it has the OPENCONTAINER flag, so as part of attacking it you also pour reagents inside
this might be solvable by making its is_open_container() proc return 0 if there isn't anything in its beaker slot

**Comment by rpilcrow** [comment]
i've done some actual tests and found that beakers don't actually do this, i was just being a big retard and making assumptions
anyhow having properly tested this ingame i've found that this IS related to chemmasters having the flag, but only glasses (and presumably other non-beaker reagent containers) care about it, as beakers have a list of objects they can be placed into and therefore do not add reagents to
