### ISSUE TITLE
Shuttle Tracking Speeds are broken.

### ISSUE THREAD

**Issue by GySgtMurphy** [Citadel-Station-13/Citadel-Station-13-RP#2742]
#### Brief description of the bug

Tracking speeds of the shuttles on the overmap are broken, and not tracking correctly.

#### What you expected to happen

Shuttles to move at the speed as indicated on the shuttle control menu.

#### What actually happened

Shuttles fly as if you are dragging 2000 more tons of shit around with you. They are jumping all over the map as we fly.

#### Steps to reproduce

Fly the shuttle, and you'll see.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)

![image](https://user-images.githubusercontent.com/79298976/108462177-2ba03c80-724a-11eb-8ab4-de4d45037112.png)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Captain277** [comment]
Code error which caused this has been resolved.
