### ISSUE TITLE
tgui causes Script errors on local servers

### ISSUE THREAD

**Issue by TheLordME** [Citadel-Station-13/Citadel-Station-13-RP#2780]
#### Brief description of the bug
Since the switch to tgui my local server(and the ones of some others from what I heard) generates script errors occasionaly.
It maybe linked to simple mobs, but I cant confirm or deny that.

#### What you expected to happen
That the localy hosted server runs smooth and without any issues

#### What actually happened
Playing on the local server throws script errors quite frequenly, often when close to simple mobs, like pets, diona nymphs and space carps(those are the ones I had it happen so far)

#### Steps to reproduce
- host local server,
- join as CE
- watch as you get 20 or so pop-up windows that tell you some script caused an error

#### Code Revision
- Local server, not the actual
 
#### Anything else you may wish to add:
- picture of the error will follow shortly

**Comment by buffyuwu** [comment]
i wasnt able to replicate this. can you provide screenshots?

**Comment by TheLordME** [comment]
havent tested in a while, and currently not doing any def work
Ill close it for now if noone else has the issue and open again should it be fixed
