### ISSUE TITLE
Chat word highlight doesn't highlight second keyword in list

### ISSUE THREAD

**Issue by TheKnightofAura** [Citadel-Station-13/Citadel-Station-13-RP#2793]
#### Brief description of the bug
The highlight keyword function in the chat menu doesn't highlight the second supplied word

#### What you expected to happen
all supplied words get highlighted

#### What actually happened
only the second word does not appear

#### Steps to reproduce
- (Step 1) open the chat and enter several words to be highlighted, separated by `,`
- (Step 2) test your words
- (and so on) find out that only the second word consistantly doesn't get highlighted. putting it later down the list still functions fine.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Local commit: 22ff84afd3486346a7a9a6d94776e516d4ebdea0
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by buffyuwu** [comment]
I think this was fixed in one of the TGUI bugfix batches
