### ISSUE TITLE
Cyborgs need a lot of love. 

### ISSUE THREAD

**Issue by nik707** [Citadel-Station-13/Citadel-Station-13-RP#2808]
COMMENT BELOW ANY ITEMS YOU THINK DEPARTMENT GRIPPERS SHOULD BE ABLE TO BE PICKED UP BUT CAN'T BE. 
IE. 
Science borg grippers can't pick up x item.

I'll be doing a pretty massive PR to address as many of these as I can.

**Comment by nevimer** [comment]
Engineering cyborgs would love to be able to pick up rods and things, machine components, etc.

**Comment by MediHound** [comment]
MediHounds need a gripper to be able to deal with bottles. Especially taking the lid off of a bottle so they can use chems from made bottles on patients.
