### ISSUE TITLE
Roller bed duplication

### ISSUE THREAD

**Issue by TheLordME** [Citadel-Station-13/Citadel-Station-13-RP#2884]
#### Brief description of the bug
You can duplicate roller beds by haveing a collapsed one in hand and clicking it with a roller bed stack.
After doing so you can deploy endless amounts of roller beds from that single collapsed roller bed in your hand
This property does not disappear from others useing them, or the bed being layed on the floor.

#### What you expected to happen
Roller beds should be consumed by the roller bed stack, or atleast not be endlessly deployable

#### What actually happened
INFINITE ROLLER BEDS

#### Steps to reproduce
- Collapse roller bed
- Pick up collapsed roller bed
- Pick up a roller bed stack(needs to be empty)
- Click the collapsed roller bed with the roller bed stack
- Use the collapse roller bed in hand to deploy endless amounts of roller beds to the floor, that are all functional roller beds.

#### Code Revision
- BYOND Version: 513.1533
Server revision compiled on: 
Master commit: df16fe6319fcd3ada8a302d31ab88e9cd9efc07b
The following pull requests are currently test merged:
2866: 'Adjustments to Ship Events, Spawning & Map' by Enzo-Leon at commit 127fcb575b
2861: 'moves panic bunker drop + db connection logging before most of client/New, maybe fixes no one getting the panic bunker drop message' by silicons at commit 18a28aba6d
2874: 'i want to see forever - for real this time' by CrystalClearCC at commit 20c1862a96
2872: 'this should fix odd shadows near the lavaland base' by buffyuwu at commit b10ba60b4e

2856: 'ports a few loadout things from main' by Kraseo at commit af8f5692e1

Local commit: 2b84833c42cab76d345614b1a958242469739e53
Server tools version: 4.10.3
 
#### Anything else you may wish to add:
- ![2021-03-22 12_26_19-Window](https://user-images.githubusercontent.com/58342752/112010781-e8c2d480-8b27-11eb-997e-11054adf4a63.png)

**Comment by buffyuwu** [comment]
@silicons did #2883 fix this?

**Comment by buffyuwu** [comment]
i believe this was fixed, due to being unable to replicate the issue. but! if it wasnt feel free to comment or @ me in discord and ill re-open and take another look. :D
