### ISSUE TITLE
kitchen problems

### ISSUE THREAD

**Issue by ariever** [Citadel-Station-13/Citadel-Station-13-RP#2916]
-You can't clean microwaves with a soap

#### What you expected to happen
-the microwave would be cleaned with the soap

#### What actually happened
/obj/machinery/microwave initialization failure. Click dropped. Contact a coder or admin.

#### Steps to reproduce
1) make microwave dirty
2) click on it with soap
3) /obj/machinery/microwave initialization failure. Click dropped. Contact a coder or admin.

#### Code Revision
Server revision compiled on: 
https//github.com/Citadel-Station-13/Citadel-Station-13-RP/commit/3ad4ded3e849722c39a26a906fbc9676bb73b42f

**Comment by buffyuwu** [comment]
![Capture](https://user-images.githubusercontent.com/42501819/113127525-d8c18980-91e6-11eb-83c4-5e84d4443799.JPG)
i'm not able to reproduce this, can you be more specific? especially with regards to the error you received?

**Comment by buffyuwu** [comment]
ahhh, this issue appeared 2 days ago

**Comment by buffyuwu** [comment]
resolved
