### ISSUE TITLE
Dogborg damage to Non-Simplemobs

### ISSUE THREAD

**Issue by MediHound** [Citadel-Station-13/Citadel-Station-13-RP#2963]
## Testmerges:

Server revision compiled on: 
Master commit: 05e44418818ea15dc91473b1d4a87a9303969249
The following pull requests are currently test merged:
#2930: 'powercreeps engine smes to have 3 more normal coils and a transmission coil so it isn't literal suicide to try to run R-UST without being a tryhard and rewiring another SMES' by silicons at commit d4a6e79be2
#2929: 'Adds a message for everyone around you when you examine something. Also adds a preference to not show other people looking at the booba.' by FreeStylaLT at commit 50e531430d
#2921: 'fine you can have your sizechems back (given that this optimizes size fetish mechanics enough to not literally have people killing the server with their erp)' by silicons at commit 7d624f817a
#2919: 'unedited webedit change - you can no longer telekinetically will tesharis onto people' by silicons at commit 31693d5530
#2932: '[RTM] Language Flags Clean up, _vr merging and speech_verbs can be lists now' by TheLordME at commit 2eec724b47
#2949: 'unsquishes minitest and adds emote stuff from main' by buffyuwu at commit 3904dba678
#2931: 'the funniest PR i have ever made' by nik707 at commit 5ffa14fc40
#2938: 'makes weapons sound beefier' by MalricB at commit 4bd1b5670d
#2957: 'fixes floors' by silicons at commit cdccc09520
#2956: 'fixes stack deletion issues ' by silicons at commit bce05a6bd5
#2958: 'lets event managers+ delete mobs in a specified range' by buffyuwu at commit 0038bfedc6
#2955: 'lying can now be left or right like main' by buffyuwu at commit 0f979e3d87
#2954: 'Fixes robotics labcoat icons' by Trilbyspaceclone at commit 34f5b4d361
#2960: '[TM ONLY] Update getrev.dm' by buffyuwu at commit 76fd239430

Local commit: e2bff65437be74bfa839927fcb341603b9af4d7c
Server tools version: 4.10.5

## Reproduction:

Borgs (tested with MediHound and Pupdozer, possibly more) are not able to damage Humans, Synths, or any other non-simplemob.
The tried modules/weapons were:
Puppy Jaws
Combat Jaws
Crowbar
Fire Extinguisher
Electric Welding Tool

Regardless of harm intent, when a click happens with the selected module, the animation, sound, and text appears, but no damage happens.
Since the damage on simplemobs (rats, mimics, giant rats) works, I assume this is a bigger issue.
It has been tested on a human without a soul (admin-spawned body), which also did not work. Multiple attacks and hits, zero damage.
It has not been tested if using a Security Borg's Blaster Rifle would work.

How to reproduce:
Be a borg. Attack a person that isn't a simplemob.

During testing and a quick look at code, it was found out that this was codebased and seemingly intentional. When a borg gets e-magged (not when they get the scrambled module installed), they regain the ability to damage living beings that aren't simplemobs.
This is, in my eyes, an oversight. I understand that in the case of an Asimov lawset, this would be beneficial, but in the case of a Crewsimov lawset (like on main) or our NT Default Lawset, this is hindering.
Reason 1: Not all non-simplemobs are Crew. Pirates, Nebula Traders, and similar for example are not crew and thus should not have such an immunity when not using Asimov laws.
Reason 2: While our default lawset does have a law regarding protecting the Crew, it is not as restrictive as the Asimov/Crewsimov lawset where no damage may be done at all. In fact, even the ruling "A lesser damage to prevent a bigger damage is not allowed." does not apply in our lawset. If a situation sees it necessary to down (not talking about killing) a crewmember in order to save another Crewmember or yourself, then this is an acceptable way. Of course, one has to afterwards make sure the Crewmember doesn't die, obviously.
Reason 3: If two Crewmembers were fighting, for example the Captain and the Cook, I would by law be required to step in and help the Captain, since he is higher rank and thus takes priority in protecting over the Cook. Not saying that a Borg shouldn't try to solve things without violence, but if the Captain was already downed and the Cook kept stabbing them with a knife... you know where this leads to.

**Comment by MediHound** [comment]
> During testing and a quick look at code, it was found out that this was codebased and seemingly intentional.
This information was provided by Nic.

**Comment by silicons** [comment]
working as intended
