### ISSUE TITLE
APC frame deconstruction multiplies metal sheets

### ISSUE THREAD

**Issue by Auris456852** [Citadel-Station-13/Citadel-Station-13-RP#299]
#### Brief description of the issue
Deconstructing APC frames gives more metal than it costs to make one
#### What you expected to happen
I decon an APC frame with a wrench and get back the two sheets I just wasted. Simple enough.
#### What actually happened
I didn't get two sheets - I got five.
#### Steps to reproduce
- Make an APC frame
- Deconstruct it
- Watch the multiplying metal
#### Code Revision
- Server revision:  - 2018-08-21
9aa59ef32eb5a18cc670c45e3ba3d95247f3b611 
#### Anything else you may wish to add:
- This is fucking silly

**Comment by Poojawa** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/blob/387ef4b95ed242fe9a12ae4d311e0a4e05d8c984/code/game/machinery/wall_frames.dm#L8

this is why unified 'frame' systems are bad.

**Comment by realbuffalowing** [comment]
will be fixed in pull #1111
