### ISSUE TITLE
Trash-eater-trash indigestable

### ISSUE THREAD

**Issue by TheKnightofAura** [Citadel-Station-13/Citadel-Station-13-RP#3073]
## Round ID:
HRP

## Reproduction:
Attempt to eat several varieties of trash with the trasheater trait. Known ones include liquifood rations, 4no raisn, dip bowls, chips, fancy plates, cheesy honkers, and really most food trash bags that can come from the trash piles. (But the indigestability happens with vendor-bought food wrappers too)
Said junk won't digest under item mode 'food only' or 'digest', the latter of which really perplexes me, considering that lets you digest basically everything that gets into your stomach that trash eater normally won't let you eat.

**Comment by TheKnightofAura** [comment]
Listing things as I find them, in case it helps
Cigarette butts, Cheesie Honkers, Candy, Pistachios pack, Chips, Tray, "LiquidProtein" ration, Protein bar

Most drink containers work just fine. Shakers from the sweatmax, every drink from the soda vendors, all get digested just fine

**Comment by Zeldazackman** [comment]
Having your digest item mode set to "food only" is going to utalize something if it contains reagents such as nutriment in a burger,  alcohol in a beer bottle, etc

Whereas having your digest item mode set to "digest" will just attempt to flat out digest whatever is inside of the stomach in question, and iirc do damage based on whatever your settings are.

So if you were to have say... a "stomach" named tail or shirt or boot or whatever and had it set to do zero burn or brute while also having it's item digest mode set to digest, it'd simply make a bit of noise every so often but never really do much in terms of actually removing the items within it.

**Comment by TheKnightofAura** [comment]
That's the point I was trying to make here. Pure digest mode doesn't get rid of these things. Food-only mode also doesn't work despite similar things working. ((or at least, when I opened this. I haven't checked in the last month, but this issue has been standing for years))
