### ISSUE TITLE
Partially broken sushi (fish) recipe 

### ISSUE THREAD

**Issue by YuriDaruski** [Citadel-Station-13/Citadel-Station-13-RP#3213]
Round ID:

Round ID doesn't show up in the status panel and the link provided is dead so I don't exactly know what you want here

Issue:

-Sif (Blue meat) fish fillets do not produce Sushi logs when attempted.
(Has not be tested with one pink one blue fillet) 

Reproduction:

-Take SIf (Blue meat) fillets, place into microwave, add 20 units rice and 1 cabbage and watch as it bursts into metaphorical flames into a burnt mess.
-Take regular (pink meat) fillets, place into microwave with 20 units rice and 1 cabbage and watch is it magically works now.

**Comment by Captain277** [comment]
Reminder for next big food update: Sifshi
