### ISSUE TITLE
Handheld Translator doesn't translate right

### ISSUE THREAD

**Issue by Auris456852** [Citadel-Station-13/Citadel-Station-13-RP#323]
#### Brief description of the issue
The translator doesn't seem to actually give the player holding it a translated message.

#### What you expected to happen
It translates the Unathi language like it's meant to while I'm holding it, or at least if I examine it right as it does its thing.

#### What actually happened
The sprite showed text on it... But it didn't actually translate.

#### Steps to reproduce
- Get a handheld translator
- Get someone to talk some foreign language
- Cry as the brick's fuckin' useless

#### Code Revision
Server revision:  - 2018-09-10
ef492b9a8c5fe067ddcd49ddc9fbb6a50a750b9a 
 
#### Anything else you may wish to add:
- Translator was printed from RnD.

**Comment by realbuffalowing** [comment]
this will be fixed when pull #1083 is merged
