### ISSUE TITLE
Xenobio- slimes only attack monkies forever and don't feed.

### ISSUE THREAD

**Issue by ArbyTheDragon** [Citadel-Station-13/Citadel-Station-13-RP#332]
#### Brief description of the issue

Give a monkey to a slime to have it feed and it will simply attack it till the end of time, untill literally the body begins to gib

#### What you expected to happen

The slime to attack the monkey untill it falls down, and then glomp it. Eventually- the slime will grow.

#### What actually happened

The grey baby slime (803) has attacked Unknown!
The grey baby slime (574) has attacked Unknown!
The grey baby slime (803) has attacked Unknown!
The grey baby slime (574) has attacked Unknown!
The grey baby slime (803) has attacked Unknown!
The grey baby slime (574) has attacked Unknown!
The grey baby slime (803) has attacked Unknown!
The grey baby slime (574) has attacked Unknown!
The grey baby slime (803) has attacked Unknown!
The grey baby slime (574) has attacked Unknown!
The grey baby slime (803) has attacked Unknown!
The grey baby slime (574) has attacked Unknown!
Unknown's right foot flies off in an arc!
You hear a loud cracking sound coming from Unknown.
The grey baby slime (803) has attacked Unknown!
The grey baby slime (574) has attacked Unknown!
The grey baby slime (803) has attacked Unknown!
The grey baby slime (574) has attacked Unknown!

#### Steps to reproduce
- (Step 1) Make monkey.
- (Step 2) Give monkey to slime
- (Step 3) Slime attac.
- (Step 4) Slime attack it.
- (Step 5) It attacks...
- (Step 6) ....
- (Step 7) It still attac.
- (Step ... ?) Ugh.

#### Code Revision
- ef492b9a8c5fe067ddcd49ddc9fbb6a50a750b9a 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

[https://puu.sh/Bvvux/5fec7a1780.jpg](url) Gibbed monkey.

**Comment by ArbyTheDragon** [comment]
I've been informed that there IS a workaround, and that the slime simply needs to be fully tame. Though, I was almost certain that the slime was tame before I fed it, because taming it makes its children quicker to tame as far as I know.

At any rate, you can lock the slime into constantly attacking a monkey forever- and it will not do anything else. You can probably pull them to fix but it might take more than one person because of how slime and any mob trying to move to a tile out of reach of you can simply break a pull and even a grab sometimes.

**Comment by realbuffalowing** [comment]
just tested, they latch and feed just fine
