### ISSUE TITLE
Light Fixture frame bugged when deconstructing.

### ISSUE THREAD

**Issue by IndirectCell** [Citadel-Station-13/Citadel-Station-13-RP#3353]
## Reproduction:

Constructed a light on a west side wall in Vacant Resturant room west of engineering and everything is normal, lights up and stuff.

Then i decide to deconstruct same light, turn off light and takes off the lightbulb... then the light turns from beeing positioned on the west wall to suddenly beeing on the south wall, and wont let me interact with it in anyway like tools or destructive means.
![bilde](https://user-images.githubusercontent.com/60559077/131690746-20c60cc6-0ab8-4e18-8ec5-02e0c6a8b248.png)

as you can see it just trows the error: 

/obj/machinery/light_construct initialization failure. Click dropped. Contact a coder or admin.

**Comment by buffyuwu** [comment]
@silicons

**Comment by silicons** [comment]
report again when it breaks i'm 99.99% sure i fixed this
