### ISSUE TITLE
Maintenance drone cannot equip tools.

### ISSUE THREAD

**Issue by Yakunan** [Citadel-Station-13/Citadel-Station-13-RP#3380]
## Reproduction:

You are unable to equip tools as a maintenance drone.

I spawned on the Talon station i think that's how its called. Tried to equip my tools, didnt work. 

Im also unable to interact with various consoles. (Not sure if that ones intended)

Maybe the mob type is an issue?

Hjorthorn was contacted and asked for help.

**Comment by TheLordME** [comment]
Unable to reproduce, due to talon losing the drone fab on one of the latest remodels

**Comment by TheLordME** [comment]
@Captain277 I think this one can be closed

**Comment by Yakunan** [comment]
Oh uh yes this can be closed. It was a bit weird.

When i joined the server it didnt work. Afterwards when i rejoined or relaunched byond and rejoined it worked. Not sure why maybe i was missing some files or something but it works now.
