### ISSUE TITLE
Continuous Integration Bug

### ISSUE THREAD

**Issue by king5327** [Citadel-Station-13/Citadel-Station-13-RP#343]
#### Brief description of the issue
`The command "python tools/TagMatcher/tag-matcher.py ../.." exited with 1.`
This has been happening to a bunch of PRs lately, so I think there's an error with the CI for the repository.

#### What you expected to happen
Tests pass.

#### What actually happened
Tests failed.

#### Steps to reproduce
- Open a PR with literally any code.
- Wait a few minutes
- Get a big stamp of disapproval from Travis.
 
#### Anything else you may wish to add:
Occurs in at least 3 different PRs that would otherwise be fine:
https://travis-ci.org/Citadel-Station-13/Citadel-Station-13-RP/jobs/429694619
https://travis-ci.org/Citadel-Station-13/Citadel-Station-13-RP/jobs/429694703
https://travis-ci.org/Citadel-Station-13/Citadel-Station-13-RP/jobs/431894708

**Comment by avabee** [comment]
Fixed in #408.
