### ISSUE TITLE
Airlock issue on Arrivals of Atlas

### ISSUE THREAD

**Issue by silicons** [Citadel-Station-13/Citadel-Station-13-RP#4156]
![image](https://user-images.githubusercontent.com/2003111/171991275-864065ee-95cf-4105-ab6e-78b10f6e34c4.png)

Airlock doesn't work.
No active map testmerges.

**Comment by ktoma36** [comment]
I believe this has been fixed last time I checked. Turns out all the airlocks use phoron_lock variants which requires one of those big ass scrubbers to be linked to the controller
