### ISSUE TITLE
Issue reported from Citadel Station 13 RP - Chat bluescreen?

### ISSUE THREAD

**Issue by Nut2** [Citadel-Station-13/Citadel-Station-13-RP#4298]
Issue reported from Citadel Station 13 RP

Reporting client version: 514.1585

#### Brief description of the bug
It makes the chat blue with the NTOS thing and the error thing listed in the bottom

#### What you expected to happen
For the chat to work

#### What actually happened
it did not work

#### Steps to reproduce
- (Step 1) I do not know, I started byond
- (Step 2) started game
- (and so on) fuck

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
UnhandledRejection: NotFoundError
   at null:null
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"thelegendnut","window":{"fancy":0,"locked":0}}

Sorry if this is vague, I don't know what is happening or why it is happening.

**Comment by silicons** [comment]
fixed
