### ISSUE TITLE
Red space suit replica has no icon

### ISSUE THREAD

**Issue by realbuffalowing** [Citadel-Station-13/Citadel-Station-13-RP#446]
#### Brief description of the issue

Red space suit replica has no icon
#### What you expected to happen

The thing to have an icon
#### What actually happened
It just displays green text next to your character that says 'suit'.

#### Steps to reproduce
- (Step 1)
spawn red space suit replica
- (Step 2)
wear red space suit replica
- (and so on)
see there is no icon
#### Code Revision
Server revision:  - 2018-10-28
b6ca0c9cf7bc6fbe420ddd75bbda841a77580df7 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by avabee** [comment]
Needs retesting.
