### ISSUE TITLE
.45 pistol doesn't take .45 pistol magazines except rubber

### ISSUE THREAD

**Issue by harry3124** [Citadel-Station-13/Citadel-Station-13-RP#4562]
## Round ID:

 431

**Comment by TheLordME** [comment]
Its intended behaviour, read the description of the gun
![grafik](https://user-images.githubusercontent.com/58342752/197331678-9c7a5e1a-6a1c-4626-9ff8-95b411f0daab.png)
the guns from the side arm boxes stored in the armory load the other magazins just fine
