### ISSUE TITLE
Mining Vendor eats ID's when items are in both hands

### ISSUE THREAD

**Issue by YuriDaruski** [Citadel-Station-13/Citadel-Station-13-RP#4664]
## Reproduction:

-Take ID and insert it into the mining vendor.
-With items in both hands, attempt to remove the ID.
-Instead of spitting the ID onto the floor, like it used to and should do, instead it poofs it completely, removing it from the game. 
-experience :sadge: as all your leftover mining points are forever gone.

**Comment by Shadow-Quill** [comment]
Can't replicate on latest master.
