### ISSUE TITLE
Neon light tubes convert themselves into normal tubes upon insertion.

### ISSUE THREAD

**Issue by moonheart08** [Citadel-Station-13/Citadel-Station-13-RP#4741]
## Round ID:
661

## Reproduction:
- Remove tube
- Insert tube from `box of neon tubes`
- Watch it not work :(

**Comment by moonheart08** [comment]
![image](https://user-images.githubusercontent.com/7806367/202843058-7c5c3846-54c7-413a-8be9-9c86ed8a6a23.png)
Appears to only affect the pre-mapped fixtures in the bar? After rebuilding them it works fine.

**Comment by ktoma36** [comment]
I wonder if there's var edits on those light frames...
