### ISSUE TITLE
Select jacket sprites are invisible

### ISSUE THREAD

**Issue by KeeBepper** [Citadel-Station-13/Citadel-Station-13-RP#5507]
Issue reported from  Round ID: [1633](https://scrubby.melonmesa.com/round/1633) (Citadel Station 13 RP)

Reporting client version: 514.1589

#### Brief description of the bug
In the character setup and after spawning in, certain clothes (jackets and such)  that were been spawned in as a part of a cosmetic loadout doesn't change player sprite while worn. They are still visible while in storage.

#### What you expected to happen
The clothing is expected to be visible on my character's sprite

#### What actually happened
The clothing is invisible

#### Steps to reproduce
- (Step 1) In the loadout menu, select any piece of clothing that doesn't overwrite the standard jumpsuit
- (Step 2) The bug should be visible even in the Character Setup

#### Code Revision
- 2023-05-16T01:22:22+00:00
 
#### Anything else you may wish to add:
- For some reason, only certain items are affected. For example Bomber Jacket is invisible, while the Fancy Fur Bomber Jacket is.

**Comment by DiscordWizard** [comment]
Adding to this, it's beyond the preview. If you join in and have things like winter coats, labcoats, etc, they are all invisible. Topless station essentially.
