### ISSUE TITLE
Atlas mapping error - Removes power from medbay and security

### ISSUE THREAD

**Issue by DiscordWizard** [Citadel-Station-13/Citadel-Station-13-RP#6307]
## Testmerges: 
Round ID: [3001](https://scrubby.melonmesa.com/round/3001)
BYOND Version: 515.1609
Server revision compiled on: 2024-01-30T16:07:07+00:00
Master commit: [9a98ca946018df1e1b576281c12b8c77a5bea6e7](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/commit/9a98ca946018df1e1b576281c12b8c77a5bea6e7)
The following pull requests are currently test merged:
[#6133: '[TESTMERGE ONLY] duct tapes a 515 bug that dcs people on going to lobby' by silicons at commit fe5927943f](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/6133)
[#6297: 'Adds a heatpump that works between utility pipe and environment' by TheLordME at commit 6176322d39](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/6297)
[#6298: 'Pilot office and Planetary sensors' by TheLordME at commit a9c259f105](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/6298)
[#6300: 'Makes table unflipping actually fail if it fails' by Putnam3145 at commit 29ad253857](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/6300)
[#6302: 'Hammerhead Upgrade + Rigsuits + Baron Integrity Increase' by jakeramsay007 at commit 8f318ab81a](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/6302)

## Reproduction:

There is a line of cut wires, rock and missing wall of the security department at the second level of the Atlas

![image](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/assets/34355419/2af7c7f1-8ceb-4705-bf5a-cd1400d08971)

**Comment by DiscordWizard** [comment]
Update, those rocks apparently also deleted a section of the medbay and exposed it to the outside

**Comment by DiscordWizard** [comment]
![image](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/assets/34355419/1184f083-978e-4e38-8d54-b6fcc7a17035)
Cut off the entirety of medbay's maintenace

**Comment by jakeramsay007** [comment]
This is resolved, it was caused by my PR
