### ISSUE TITLE
[HARDSYNC] Conveyors in mining don't convey

### ISSUE THREAD

**Issue by Keekenox** [Citadel-Station-13/Citadel-Station-13-RP#670]
#### Brief description of the issue
Conveyors in mining don't convey

#### What you expected to happen
Conveyors to turn on when I turn level

#### What actually happened
Lever moved, conveyors not

#### Steps to reproduce
- (Step 1) Lever
- (Step 2) Disappointment

[https://i.imgur.com/hQAzYMi.png](url)

**Comment by realbuffalowing** [comment]
this needs to be closed ily
