### ISSUE TITLE
Cannot deconstruct xenobotany equipment; creates frames instead.

### ISSUE THREAD

**Issue by rpilcrow** [Citadel-Station-13/Citadel-Station-13-RP#710]
Attempting to deconstruct (screwdriver > crowbar) the bioballistic delivery system or lysis-isolation centrifuge will instead simply spawn an empty frame, without removing the original object. This presumably also shits out runtimes, but I haven't been able to check that yet.

They are also unwrenchable, meaning that they cannot be moved around the lab if needed. Combined with the inability to move the smartfridge, this means that it is impossible to get an optimal setup for the lab without asking an admin or editing the map files.

2019-02-14, Code rev 532dbd2f57b6bcfe183f5995c494229d0f7bdc84

**Comment by realbuffalowing** [comment]
i'm 99% sure they are specialized machines and therefore not meant to be deconstructed/moved around
if you want to PR a rework of them be my guest, but this isnt really an issue

from a lore perspective, why would anyone go around disassembling/reassembling highly advanced specialized lab equipment? from a code perspective, im pretty sure they need to be adjacent to each other or things will break
