### ISSUE TITLE
Sprite issue related to dragon tail and poncho

### ISSUE THREAD

**Issue by SimonTheMiner** [Citadel-Station-13/Citadel-Station-13-RP#789]
#### Brief description of the issue
The dragon tail under the vore tab in character creation shows through the poncho, despite the poncho being in front of it.

#### What you expected to happen
Poncho to cover tail shown between legs when viewing from the front

#### What actually happened
When viewing front of sprite you can see the tail through the poncho

#### Steps to reproduce
Use dragon tail as customization on vore tab
Use poncho on loadout

#### Code Revision
0a189184aa6ba4d979e0c7a7059696681e1139c4 
 
#### Anything else you may wish to add:
https://gyazo.com/fda7ec020bb384f84685b187efd5d9a8
Tail was colored green for visibility
https://gyazo.com/c79dd3b8617c714183ca5e02fe9b6f85
What the poncho should look like

**Comment by realbuffalowing** [comment]
https://puu.sh/DaZJC/13f80344c4.png
i fix, adding to pr #1112
