### ISSUE TITLE
Neither Zorren species can speak Terminus.

### ISSUE THREAD

**Issue by Kiroberos** [Citadel-Station-13/Citadel-Station-13-RP#847]
#### Brief description of the issue
I have a Flatland Zorren.  No custom species.  Flatland Zorren ears and a Vulp tail from the VORE menu.  No custom species named there either.  When I get in-game, I can understand Terminus just fine, but not speak it.  It's supposed to be their native language.  Tried remaking as a Highlander Zorren, but same issue.

#### What you expected to happen
Being able to speak Terminus using ,4, as it says on the known languages.

#### What actually happened
Known Language says this:
Terminus (,4) - cannot speak!
Trying to talk using Terminus doesn't parse the ,4, instead inserting it into the message.

#### Steps to reproduce
Just make either type of Zorren and try speaking as their native language.

#### Code Revision
Server revision:  - 2019-03-17
b909fa0fe5577d3745d8d06fbadd0ce0517407ed

**Comment by realbuffalowing** [comment]
plz close this issue maintainer men
